// Checklist de competencias de la rotación.
// nivel = nivel esperado al final de la rotación:
//   "O" = observar (ha visto realizarlo)
//   "A" = hacer acompañada (lo realiza con supervisión directa)
//   "S" = hacer con supervisión indirecta (lo realiza y la tutora lo valida)
// La evaluación la realiza la tutora. La app solo permite a la alumna marcar
// su propio progreso y exportar la lista para la firma.
window.CHECKLIST = [
  { bloque: "centro", titulo: "Cómo funciona el centro", items: [
    { id: "c01", texto: "Conoce a los miembros del EAP y qué hace cada uno", nivel: "S" },
    { id: "c02", texto: "Distingue los tipos de cita y sabe leer la agenda del día", nivel: "S" },
    { id: "c03", texto: "Sabe dónde están el carro de parada, el DEA, el oxígeno y la sala de urgencias", nivel: "S" },
    { id: "c04", texto: "Conoce el circuito de notificación de accidente biológico del centro", nivel: "S" },
    { id: "c05", texto: "Se presenta al paciente como estudiante y pide su consentimiento", nivel: "S" },
    { id: "c06", texto: "Realiza un registro clínico completo y objetivo, validado por la tutora", nivel: "A" },
    { id: "c07", texto: "Aplica la identificación inequívoca antes de cualquier técnica", nivel: "S" },
    { id: "c08", texto: "Higiene de manos en los cinco momentos", nivel: "S" },
    { id: "c09", texto: "Explica qué es la Cartera de Servicios y el Contrato Programa y localiza un indicador en la consulta", nivel: "S" },
  ]},
  { bloque: "extracciones", titulo: "Sala de extracciones", items: [
    { id: "e01", texto: "Comprueba la petición, el ayuno y las condiciones preanalíticas", nivel: "S" },
    { id: "e02", texto: "Prepara el material y los tubos según la petición", nivel: "S" },
    { id: "e03", texto: "Elige la vena por palpación y coloca el compresor menos de un minuto", nivel: "S" },
    { id: "e04", texto: "Realiza venopunción con sistema de vacío", nivel: "S" },
    { id: "e05", texto: "Realiza venopunción con palomilla", nivel: "A" },
    { id: "e06", texto: "Respeta el orden de extracción y homogeneiza correctamente cada tubo", nivel: "S" },
    { id: "e07", texto: "Etiqueta y envía las muestras según el circuito del centro", nivel: "S" },
    { id: "e08", texto: "Actúa correctamente ante una lipotimia vasovagal", nivel: "A" },
    { id: "e09", texto: "Realiza extracción en domicilio", nivel: "A" },
    { id: "e10", texto: "Explica al paciente la recogida de orina, urocultivo y sangre oculta en heces", nivel: "S" },
    { id: "e11", texto: "Revisa una hoja de incidencias del laboratorio con la tutora", nivel: "O" },
  ]},
  { bloque: "urgencias", titulo: "Urgencias en el centro", items: [
    { id: "u01", texto: "Participa en una revisión completa del carro de parada", nivel: "A" },
    { id: "u02", texto: "Demuestra la secuencia de SVB con DEA en adulto (simulación)", nivel: "A" },
    { id: "u03", texto: "Demuestra las diferencias del SVB pediátrico (simulación)", nivel: "A" },
    { id: "u04", texto: "Monitoriza constantes en una urgencia: TA, FC, saturación, glucemia", nivel: "A" },
    { id: "u05", texto: "Realiza un ECG urgente en menos de 10 minutos ante dolor torácico", nivel: "A" },
    { id: "u06", texto: "Conoce la localización y preparación del material de anafilaxia", nivel: "S" },
    { id: "u07", texto: "Atiende una hipoglucemia en paciente consciente", nivel: "A" },
    { id: "u08", texto: "Sabe qué información se transmite al 112 y quién la da", nivel: "S" },
    { id: "u09", texto: "Ha observado o participado en la atención de al menos una urgencia real", nivel: "O" },
  ]},
  { bloque: "domicilios", titulo: "Avisos domiciliarios", items: [
    { id: "d01", texto: "Prepara el maletín y revisa la historia antes de salir", nivel: "S" },
    { id: "d02", texto: "Acompaña en al menos tres visitas domiciliarias", nivel: "A" },
    { id: "d03", texto: "Cumplimenta Barthel y otra escala de valoración en domicilio", nivel: "A" },
    { id: "d04", texto: "Valora el entorno: barreras, medicación real, alimentación, apoyo social", nivel: "A" },
    { id: "d05", texto: "Valora la sobrecarga del cuidador principal", nivel: "A" },
    { id: "d06", texto: "Realiza una cura en domicilio", nivel: "A" },
    { id: "d07", texto: "Gestiona correctamente residuos y biopunzantes fuera del centro", nivel: "S" },
    { id: "d08", texto: "Registra la visita domiciliaria y su plan de cuidados", nivel: "A" },
  ]},
  { bloque: "tecnicas", titulo: "Técnicas de consulta", items: [
    { id: "t01", texto: "Toma la TA con técnica correcta y manguito adecuado", nivel: "S" },
    { id: "t02", texto: "Enseña a un paciente la técnica de AMPA", nivel: "A" },
    { id: "t03", texto: "Coloca y retira un MAPA", nivel: "A" },
    { id: "t04", texto: "Realiza un ECG de 12 derivaciones sin artefactos y bien identificado", nivel: "S" },
    { id: "t05", texto: "Prepara e instruye al paciente para una espirometría", nivel: "A" },
    { id: "t06", texto: "Realiza una espirometría con maniobras aceptables y reproducibles", nivel: "A" },
    { id: "t07", texto: "Realiza glucemia capilar y educa en la técnica", nivel: "S" },
    { id: "t08", texto: "Administra vacunas en adulto por vía intramuscular y subcutánea", nivel: "S" },
    { id: "t09", texto: "Comprueba y registra la cadena de frío de la nevera de vacunas", nivel: "S" },
    { id: "t10", texto: "Registra una vacuna en el sistema de información vacunal", nivel: "A" },
    { id: "t11", texto: "Retira puntos o grapas", nivel: "S" },
    { id: "t12", texto: "Realiza un sondaje vesical", nivel: "A" },
    { id: "t13", texto: "Realiza un lavado ótico", nivel: "A" },
    { id: "t14", texto: "Realiza un ITB con Doppler e interpreta el resultado", nivel: "A" },
    { id: "t15", texto: "Realiza un test rápido (faríngeo, orina o antígenos) con muestra correcta", nivel: "S" },
  ]},
  { bloque: "pediatria", titulo: "Pediatría en Primaria", items: [
    { id: "p01", texto: "Participa en consultas del programa del niño sano de distintas edades", nivel: "A" },
    { id: "p02", texto: "Pesa, talla y mide el perímetro cefálico de un lactante con técnica correcta", nivel: "S" },
    { id: "p03", texto: "Registra e interpreta percentiles con la familia", nivel: "A" },
    { id: "p04", texto: "Valora hitos del desarrollo según edad y reconoce señales de alarma", nivel: "A" },
    { id: "p05", texto: "Vacuna a un lactante en vasto externo con medidas de reducción del dolor", nivel: "A" },
    { id: "p06", texto: "Vacuna a un niño mayor en deltoides con distracción y sujeción adecuada", nivel: "A" },
    { id: "p07", texto: "Comprueba el calendario vacunal vigente y detecta un calendario incompleto", nivel: "A" },
    { id: "p08", texto: "Valora a un niño con fiebre y explica los signos de alarma a la familia", nivel: "A" },
    { id: "p09", texto: "Observa una toma de lactancia materna y valora posición y agarre", nivel: "A" },
    { id: "p10", texto: "Da consejo sobre alimentación complementaria y prevención de atragantamiento", nivel: "A" },
  ]},
  { bloque: "cronicos", titulo: "Crónicos", items: [
    { id: "k01", texto: "Lleva una consulta programada de HTA con supervisión", nivel: "A" },
    { id: "k02", texto: "Lleva una consulta programada de DM2 con supervisión", nivel: "A" },
    { id: "k03", texto: "Lleva una consulta programada de EPOC con supervisión", nivel: "A" },
    { id: "k04", texto: "Educa en técnica de inhaladores y comprueba la técnica del paciente", nivel: "S" },
    { id: "k05", texto: "Educa en técnica de insulina y rotación de zonas", nivel: "A" },
    { id: "k06", texto: "Revisa la adherencia y la medicación real de un paciente crónico", nivel: "A" },
    { id: "k07", texto: "Localiza en la historia los indicadores de HTA, DM2 y EPOC del Contrato Programa", nivel: "A" },
    { id: "k08", texto: "Calcula y registra el riesgo cardiovascular", nivel: "A" },
  ]},
  { bloque: "heridas", titulo: "Heridas y curas", items: [
    { id: "h01", texto: "Valora una herida crónica: tipo, lecho, bordes, exudado, piel perilesional", nivel: "A" },
    { id: "h02", texto: "Aplica el esquema TIME en la preparación del lecho", nivel: "A" },
    { id: "h03", texto: "Realiza una cura de úlcera venosa", nivel: "A" },
    { id: "h04", texto: "Aplica o retira un vendaje compresivo con supervisión", nivel: "A" },
    { id: "h05", texto: "Valora el riesgo de UPP con Braden y planifica prevención", nivel: "S" },
    { id: "h06", texto: "Realiza una cura de UPP según estadio", nivel: "A" },
    { id: "h07", texto: "Elige el apósito adecuado y justifica la elección", nivel: "A" },
    { id: "h08", texto: "Realiza una exploración completa de pie diabético (monofilamento, diapasón, pulsos)", nivel: "A" },
    { id: "h09", texto: "Clasifica el riesgo de pie diabético y registra la exploración", nivel: "A" },
    { id: "h10", texto: "Realiza educación sobre cuidado del pie y calzado", nivel: "S" },
    { id: "h11", texto: "Registra una cura con escala de evolución (PUSH o RESVECH)", nivel: "A" },
  ]},
  { bloque: "comunidad", titulo: "Comunidad, cribados y comunicación", items: [
    { id: "m01", texto: "Asiste a una actividad grupal o comunitaria del centro", nivel: "O" },
    { id: "m02", texto: "Identifica activos en salud del barrio y recomienda uno a un paciente", nivel: "A" },
    { id: "m03", texto: "Explica el kit de sangre oculta en heces a una persona del programa de cribado", nivel: "S" },
    { id: "m04", texto: "Informa sobre los programas de cribado de cérvix y mama", nivel: "A" },
    { id: "m05", texto: "Usa preguntas abiertas, resumen y teach-back en una consulta", nivel: "A" },
    { id: "m06", texto: "Aplica elementos de entrevista motivacional en un cambio de hábito", nivel: "A" },
    { id: "m07", texto: "Adapta la comunicación a la edad del niño y a la familia", nivel: "A" },
  ]},
];
