window.BLOQUES = window.BLOQUES || [];

window.BLOQUES.push({
  id: "heridas",
  n: 8,
  tapon: "rosa",
  color: "#B4527A",
  titulo: "Heridas y curas",
  sub: "Heridas crónicas, úlceras y exploración del pie diabético. Se cura todas las semanas de la rotación.",
  semana: "Todas las semanas",
  temas: [
  { id:"her-1", titulo:"Heridas · Conceptos generales, ambiente húmedo y biofilm", min:4, html:`
<h3>Conceptos generales de herida crónica</h3>
<h4>1.1 Definición y fisiopatología</h4>
<p>Una herida crónica es aquella que no sigue el proceso normal de cicatrización en un tiempo esperado (generalmente > 4-6 semanas), o que recidiva con frecuencia. Su mantenimiento obedece a factores locales y sistémicos que perpetúan el estado inflamatorio.</p>
<h4><em>Fases de la cicatrización (y por qué se bloquean)</em></h4>
<div class="tbl-scroll"><table><tr><th>Fase</th><th>Qué puede bloquearlo</th></tr><tr><td><strong>Hemostasia</strong></td><td>Vasoconstricción, activación plaquetaria. Se interrumpe en coagulopatías o uso de anticoagulantes.</td></tr><tr><td><strong>Inflamación</strong></td><td>Limpieza de debris y bacterias. Se cronifica si hay infección, biofilm o isquemia.</td></tr><tr><td><strong>Proliferación</strong></td><td>Formación de tejido de granulación y epitelización. Bloqueada por hipoxia tisular, desnutrición o corticoides.</td></tr><tr><td><strong>Remodelación</strong></td><td>Maduración del colágeno (hasta 2 años). Alterada en diabetes, envejecimiento, tabaco.</td></tr></table></div>
<h4>1.2 Principios del ambiente húmedo (TIME)</h4>
<p>El paradigma de cuidado de heridas crónicas se articula en el acrónimo TIME, propuesto por el European Wound Management Association (EWMA):</p>
<div class="callout alerta"><span class="lbl">T — Tissue (tejido no viable)</span><p>Desbridamiento del tejido necrótico, esfacelado o desvitalizado. El tejido muerto sustenta biofilm e impide la granulación.</p></div>
<div class="callout truco"><span class="lbl">I — Infection/Inflammation (infección / inflamación)</span><p>Control de la carga bacteriana. Distinguir contaminación → colonización → infección local → infección invasiva. El biofilm es el principal obstáculo.</p></div>
<div class="callout truco"><span class="lbl">M — Moisture (humedad)</span><p>Mantener equilibrio de exudado: ni exceso (maceración) ni defecto (desecación). Elección del apósito según nivel de exudado.</p></div>
<div class="callout truco"><span class="lbl">E — Edge (bordes / epitelización)</span><p>Estimular la migración epitelial desde los bordes. Bordes socavados, rodados o callosos indican estancamiento.</p></div>
<h4>1.3 Biofilm: el enemigo silencioso</h4>
<p>El biofilm es una comunidad de microorganismos embebidos en una matriz extracelular que les confiere alta resistencia a antibióticos y antisépticos. Presente en > 78% de las heridas crónicas. Su sospecha clínica debe activar el protocolo ABCD del biofilm:</p>
<ul><li>A — Antiséptico tópico (ej. PHMB, cadexómero yodado)</li><li>B — Biocida mecánico (desbridamiento físico riguroso)</li><li>C — Control del exudado (apósito adecuado)</li><li>D — Dispersante (si disponible, surfactantes como betaína)</li></ul>
` },
  { id:"her-2", titulo:"Heridas · Úlceras venosas", min:4, html:`
<h3>Úlceras venosas</h3>
<h4>2.1 Fisiopatología</h4>
<p>La insuficiencia venosa crónica (IVC) genera hipertensión venosa → extravasación de eritrocitos → depósito de hemosiderina → hiperpigmentación. La inflamación crónica deteriora el lecho capilar y genera la úlcera.</p>
<h4>2.2 Características clínicas</h4>
<div class="tbl-scroll"><table><tr><th>Característica</th><th>Descripción</th></tr><tr><td><strong>Localización</strong></td><td>Tercio inferior de la pierna, área maleolar interna (gamastre)</td></tr><tr><td><strong>Forma</strong></td><td>Irregular, bordes poco definidos, superficial</td></tr><tr><td><strong>Fondo</strong></td><td>Fibrina amarillenta, tejido de granulación rojo, exudado moderado-abundante</td></tr><tr><td><strong>Piel perilesional</strong></td><td>Lipodermatoesclerosis, eccema, hiperpigmentación, edema</td></tr><tr><td><strong>Dolor</strong></td><td>Moderado, mejora con elevación de MMII</td></tr><tr><td><strong>Pulsos</strong></td><td>Presentes (descartar componente arterial: ITB > 0,8)</td></tr></table></div>
<h4>2.3 Evaluación: Índice Tobillo-Brazo (ITB)</h4>
<p>Imprescindible antes de aplicar terapia compresiva. Se mide con Doppler portátil.</p>
<div class="tbl-scroll"><table><tr><th>ITB</th><th>Interpretación y conducta</th></tr><tr><td><strong>> 1,3</strong></td><td>Calcificación arterial (diabetes, IRC) — no fiable</td></tr><tr><td><strong>0,9 – 1,3</strong></td><td>Normal → compresión fuerte indicada</td></tr><tr><td><strong>0,6 – 0,8</strong></td><td>IVC con componente arterial leve → compresión reducida</td></tr><tr><td><strong>< 0,6</strong></td><td>Isquemia crítica → CONTRAINDICADA la compresión</td></tr></table></div>
<h4>2.4 Protocolo de tratamiento</h4>
<h4><em>Paso 1 — Limpieza</em></h4>
<p>Suero fisiológico a temperatura ambiente o agua corriente. Evitar antisépticos citotóxicos en lecho limpio (povidona en lecho granulante = daño epitelial).</p>
<h4><em>Paso 2 — Desbridamiento si procede</em></h4>
<ul><li>Autolítico: hidrogeles, hidrocoloides (lesiones con fibrina moderada)</li><li>Enzimático: colagenasa (tejido necrótico seco o mixto)</li><li>Mecánico / cortante: si urgencia o necrosis extensa</li></ul>
<h4><em>Paso 3 — Control del exudado y biofilm</em></h4>
<ul><li>Exudado moderado-alto: espumas de poliuretano, alginatos</li><li>Sospechar biofilm: PHMB, cadexómero yodado, plata en infección local</li></ul>
<h4><em>Paso 4 — Terapia compresiva (PIEDRA ANGULAR)</em></h4>
<p>Sin compresión no hay cicatrización en úlcera venosa. La compresión reduce la hipertensión venosa.</p>
<div class="tbl-scroll"><table><tr><th>Tipo</th><th>Indicación</th></tr><tr><td><strong>Sistema de 4 capas</strong></td><td>Gold standard. 40 mmHg tobillo. Alta eficacia.</td></tr><tr><td><strong>Venda de corta extensión</strong></td><td>Ej. Rosidal K. Buena para pacientes activos.</td></tr><tr><td><strong>Sistema de 2 capas</strong></td><td>Ej. Coban 2. Cómodo, mantiene presión 7 días.</td></tr><tr><td><strong>Media de compresión</strong></td><td>Mantenimiento tras cicatrización. Clase II-III.</td></tr></table></div>
<div class="callout truco"><span class="lbl">⚠ Clave clínica — Recidiva</span><p>La tasa de recidiva de la úlcera venosa es del 60-70% sin media de compresión de mantenimiento. La educación del paciente sobre adherencia a la compresión es parte del tratamiento.</p></div>
` },
  { id:"her-3", titulo:"Heridas · Úlceras por presión", min:4, html:`
<h3>Úlceras por presión (UPP)</h3>
<h4>3.1 Definición y etiopatogenia</h4>
<p>Lesión localizada en la piel y/o tejidos subyacentes, generalmente sobre una prominencia ósea, resultado de presión o presión en combinación con fuerzas de cizalla. La isquemia tisular aparece con presiones > 32 mmHg mantenidas > 2 horas.</p>
<h4>3.2 Factores de riesgo — Escala Braden</h4>
<p>La escala de Braden evalúa 6 subescalas (percepción sensorial, humedad, actividad, movilidad, nutrición, fricción/cizalla). Puntuación ≤ 18 indica riesgo.</p>
<div class="tbl-scroll"><table><tr><th>Puntuación Braden</th><th>Conducta</th></tr><tr><td><strong>15-18</strong></td><td>Riesgo bajo → revisión cada 48h</td></tr><tr><td><strong>13-14</strong></td><td>Riesgo moderado → cambios posturales cada 2h, SEMP</td></tr><tr><td><strong>10-12</strong></td><td>Riesgo alto → protocolo intensivo de prevención</td></tr><tr><td><strong>≤ 9</strong></td><td>Riesgo muy alto → máxima alerta, superficies dinámicas</td></tr></table></div>
<h4>3.3 Clasificación NPUAP/EPUAP (estadios)</h4>
<div class="tbl-scroll"><table><tr><th>Estadio</th><th>Descripción</th><th>Característica clave</th></tr><tr><td><strong>Estadio I</strong></td><td>Eritema no blanqueable en piel intacta</td><td>Piel íntegra pero con enrojecimiento persistente. Sin pérdida de tejido.</td></tr><tr><td><strong>Estadio II</strong></td><td>Pérdida parcial del espesor dérmico</td><td>Úlcera superficial, lecho rojo-rosado. Puede presentarse como ampolla.</td></tr><tr><td><strong>Estadio III</strong></td><td>Pérdida total del espesor cutáneo</td><td>Tejido subcutáneo visible. No afecta fascia, hueso o tendón.</td></tr><tr><td><strong>Estadio IV</strong></td><td>Pérdida total de tejido, afectación profunda</td><td>Expone hueso, tendón o músculo. Riesgo de osteomielitis.</td></tr><tr><td><strong>No clasificable</strong></td><td>Profundidad desconocida</td><td>Cubierta por esfacelo o escara. Valorar tras desbridamiento.</td></tr><tr><td><strong>Lesión por presión en tejidos profundos</strong></td><td>LPP-PP</td><td>Decoloración rojo oscuro/morado en piel intacta. Puede evolucionar rápidamente.</td></tr></table></div>
<h4>3.4 Prevención — Las 5 P</h4>
<ul><li>Presión: cambios posturales cada 2h (decúbito) o 15' (sedestación)</li><li>Piel: valoración diaria, hidratación, control de la humedad (incontinencia)</li><li>Posicionamiento: alineación correcta, talones flotantes</li><li>Productos: superficies especiales de manejo de presión (SEMP) estáticas o dinámicas</li><li>Protocolo: nutrición, hidratación, educación al cuidador</li></ul>
<h4>3.5 Tratamiento local según estadio</h4>
<div class="tbl-scroll"><table><tr><th>Estadio</th><th>Abordaje local</th></tr><tr><td><strong>Estadio I</strong></td><td>Apósito protector (film transparente, hidrocoloide fino). Aliviar presión. NO masajear.</td></tr><tr><td><strong>Estadio II</strong></td><td>Hidrofibra o espuma. Control de humedad. Desbridamiento si ampolla rota infectada.</td></tr><tr><td><strong>Estadio III-IV</strong></td><td>Desbridamiento previo. Apósito según fase: alginato/hidrofibra si exudado alto, espuma si moderado. Valorar TPN.</td></tr><tr><td><strong>No clasificable</strong></td><td>Mantener escara seca en talón sin signos de infección ("escara estable"). Si hay fluctuación: desbridar.</td></tr></table></div>
` },
  { id:"her-4", titulo:"Heridas · Herida crónica compleja y pie diabético", min:4, html:`
<h3>Herida crónica compleja y pie diabético</h3>
<h4>4.1 Pie diabético — Definición y fisiopatología</h4>
<p>El pie diabético engloba las alteraciones que aparecen en el pie del paciente diabético, resultado de la combinación de neuropatía, enfermedad arterial periférica (EAP) e infección. Es la primera causa de amputación no traumática.</p>
<div class="tbl-scroll"><table><tr><th>Mecanismo</th><th>Consecuencia clínica</th></tr><tr><td><strong>Neuropatía sensorial</strong></td><td>Pérdida de la sensación protectora → traumatismos inadvertidos</td></tr><tr><td><strong>Neuropatía motora</strong></td><td>Atrofia de músculos intrínsecos → deformidades (dedos en garra)</td></tr><tr><td><strong>Neuropatía autonómica</strong></td><td>Piel seca, fisuras, anhidrosis → puerta de entrada para infección</td></tr><tr><td><strong>EAP</strong></td><td>Isquemia → mala perfusión → dificultad de cicatrización</td></tr><tr><td><strong>Inmunosupresión relativa</strong></td><td>Mayor susceptibilidad a infección, biofilm agresivo</td></tr></table></div>
<h4>4.2 Clasificación de Wagner</h4>
<div class="tbl-scroll"><table><tr><th>Grado</th><th>Descripción</th></tr><tr><td><strong>Grado 0</strong></td><td>Pie en riesgo. Sin úlcera activa. Deformidades, callos.</td></tr><tr><td><strong>Grado 1</strong></td><td>Úlcera superficial. No afecta tejido subcutáneo.</td></tr><tr><td><strong>Grado 2</strong></td><td>Úlcera profunda. Afecta tendón, cápsula, hueso no infectado.</td></tr><tr><td><strong>Grado 3</strong></td><td>Úlcera profunda con osteomielitis o absceso.</td></tr><tr><td><strong>Grado 4</strong></td><td>Gangrena localizada (dedo, antepié).</td></tr><tr><td><strong>Grado 5</strong></td><td>Gangrena extensa. Amputación mayor necesaria.</td></tr></table></div>
<h4>4.3 Evaluación del pie diabético en consulta de enfermería</h4>
<ul><li>Exploración vascular: pulsos pedios y tibiales posteriores, ITB, tiempo de relleno capilar</li><li>Exploración neurológica: monofilamento 10g (Semmes-Weinstein), diapasón 128Hz, test del algodón</li><li>Exploración dermatológica: hidratación, fisuras, callos, onicomicosis, deformidades</li><li>Control glucémico: HbA1c, glucemia capilar</li><li>Educación terapéutica: inspección diaria del pie, calzado adecuado, higiene, consulta precoz</li></ul>
<div class="callout alerta"><span class="lbl">⚠ Señales de alarma — derivación urgente</span><p>Celulitis > 2 cm, crepitación (gas), afectación articular, fiebre, glucemia descontrolada, úlcera Wagner ≥ 3. Derivar a urgencias hospitalarias.</p></div>
<h4>4.4 Herida crónica compleja — concepto y abordaje</h4>
<p>Se considera herida crónica compleja aquella con ≥ 1 de los siguientes criterios: más de 3 meses de evolución sin respuesta a tratamiento estándar, herida de difícil acceso o manejo, necesidad de terapias avanzadas, afectación de la calidad de vida del paciente.</p>
<h4><em>Terapias avanzadas a considerar (coordinadas con equipo referente)</em></h4>
<ul><li>TPN (Terapia de Presión Negativa): estimula granulación, reduce edema. Indicación: heridas cavitadas, pie diabético Wagner 2-3, postquirúrgicas.</li><li>Injertos biológicos / matrices dérmicas: en heridas sin progresión tras 4 semanas de tratamiento correcto.</li><li>Factores de crecimiento (PDGF): becaplermin en pie diabético neuropático grado 1-2.</li><li>Oxigenoterapia hiperbárica: isquemia crítica no revascularizable, osteomielitis refractaria.</li><li>Sevoflurano tópico: analgesia en curas de heridas complejas dolorosas (uso compasivo en España).</li></ul>
` },
  { id:"her-5", titulo:"Heridas · Productos y apósitos", min:4, html:`
<h3>Productos y apósitos — clasificación práctica</h3>
<h4>5.1 Selección del apósito: algoritmo básico</h4>
<p>La elección del apósito depende de 4 variables: nivel de exudado, presencia de infección/biofilm, estado del tejido (lecho) y estado de la piel perilesional.</p>
<div class="tbl-scroll"><table><tr><th>Situación clínica</th><th>Apósito de elección</th></tr><tr><td><strong>Exudado NULO / escaso</strong></td><td>Hidrogel, hidrocoloide fino, film de poliuretano</td></tr><tr><td><strong>Exudado MODERADO</strong></td><td>Espuma de poliuretano (con o sin borde adhesivo), hidrocoloide</td></tr><tr><td><strong>Exudado ALTO / muy alto</strong></td><td>Alginato cálcico, hidrofibra (Aquacel®), carbón activo si maloliente</td></tr><tr><td><strong>INFECCIÓN local confirmada</strong></td><td>Plata (sulfadiazina argéntica, Mepilex Border Ag®), cadexómero yodado, PHMB</td></tr><tr><td><strong>BIOFILM sospechado</strong></td><td>PHMB (Prontosan®), betaína + PHMB, surfactantes, desbridamiento mecánico</td></tr><tr><td><strong>Tejido NECRÓTICO seco</strong></td><td>Hidrogel hidratante + oclusión, colagenasa enzimática</td></tr><tr><td><strong>Tejido FIBRINO-ESFACELADO</strong></td><td>Autolítico (hidrocoloide), desbridamiento cortante si urgencia</td></tr><tr><td><strong>GRANULACIÓN activa</strong></td><td>Espuma no adherente, hidrofibra. Evitar cambios frecuentes (> 3-4 días).</td></tr><tr><td><strong>Fase de EPITELIZACIÓN</strong></td><td>Film transparente, silicona, hidrocoloide muy fino. Mínima frecuencia de cambio.</td></tr><tr><td><strong>Piel perilesional MACERADA</strong></td><td>Protección con pasta de zinc (Cytelium®), film, crema de barrera</td></tr><tr><td><strong>Cavidades / tunelizaciones</strong></td><td>Alginato en cinta, hidrofibra en cinta, espumas de relleno. NO taponar fuerte.</td></tr></table></div>
<h4>5.2 Fichas de productos habituales</h4>
<div class="tbl-scroll"><table><tr><th>Producto</th><th>Indicación principal</th><th>Notas clave</th></tr><tr><td><strong>Hidrogel (ej. Intrasite®)</strong></td><td>Relleno, escara seca, autolisis</td><td>Mantener ocluido. Cambiar cada 1-3 días. No usar en infección activa sin antiséptico.</td></tr><tr><td><strong>Hidrocoloide (ej. DuoDERM®)</strong></td><td>Exudado bajo-moderado, epitelización</td><td>No dejar >7 días. El cambio de color/olor del gel es normal, no infección.</td></tr><tr><td><strong>Espuma (ej. Mepilex®)</strong></td><td>Exudado moderado-alto, granulación</td><td>Silicona = no traumático. Cambiar cuando saturado o cada 3-7 días.</td></tr><tr><td><strong>Alginato (ej. Sorbalgon®)</strong></td><td>Exudado alto, hemostasia</td><td>Requiere exudado para activarse. En seco → desecación. No cortar con tijeras metálicas.</td></tr><tr><td><strong>Hidrofibra (Aquacel®)</strong></td><td>Exudado alto, cavidades</td><td>Fibras de CMC. Transforma el exudado en gel. Muy absorbente. Cinta para cavidades.</td></tr><tr><td><strong>Plata (ej. Aquacel Ag®)</strong></td><td>Infección local, biofilm bacteriano</td><td>Máx. 2-4 semanas continuas. Revisar necesidad. No en alergia a plata.</td></tr><tr><td><strong>PHMB (Prontosan®)</strong></td><td>Limpieza, biofilm, inflamación crónica</td><td>Polihexanida + betaína. Irriga o en gasa impregnada. Muy buena tolerancia.</td></tr><tr><td><strong>Cadexómero yodado (Iodosorb®)</strong></td><td>Exudado alto + infección / biofilm</td><td>Libera yodo de forma sostenida. Contraindicado en embarazo, tiroidopatía.</td></tr><tr><td><strong>Pasta de zinc (Cytelium®)</strong></td><td>Maceración perilesional</td><td>Aplicar SOLO en piel perilesional, no en lecho. Barrera física excelente.</td></tr><tr><td><strong>Film de poliuretano (Tegaderm®)</strong></td><td>Piel íntegra de riesgo, fijación IV, epitelización</td><td>Semipermeable. No absorbe exudado. No usar en heridas exudativas.</td></tr></table></div>
<h4>5.3 Frecuencia de cura: principio de mínima intervención</h4>
<p>La tendencia actual (Conde Montero) es reducir la frecuencia de cura al mínimo necesario. Cada cura es un trauma. Los apósitos modernos permiten intervalos de 3-7 días cuando el lecho lo permite.</p>
<ul><li>Aumentar frecuencia solo si: signos de infección, saturación del apósito, fiebre, dolor no controlado</li><li>Reducir frecuencia si: herida limpia, apósito no saturado, buena evolución</li></ul>
<div class="callout truco"><span class="lbl">Regla práctica</span><p>Si al retirar el apósito no hay cambios relevantes → el cambio fue innecesario. La herida que mejora no necesita que la "vigilemos" a diario.</p></div>
` },
  { id:"her-6", titulo:"Heridas · Evaluación: escalas y registro", min:4, html:`
<h3>Evaluación de heridas — escalas e instrumentos</h3>
<h4>6.1 Escala PUSH (Pressure Ulcer Scale for Healing)</h4>
<p>Monitoriza la evolución de UPP. Evalúa 3 ítems: tamaño de la lesión (0-10), cantidad de exudado (0-3) y tipo de tejido en el lecho (0-4). Puntuación total 0-17. A menor puntuación, mejor evolución.</p>
<p><strong>6.2 Escala RESVECH 2.0 (Resultado Esperado de la Valoración y Evolución de la Cicatrización de las Heridas)</strong></p>
<p>Desarrollada en España (grupo de enfermería). Evalúa 6 dimensiones: dimensiones de la lesión, profundidad, bordes, tipo de tejido, exudado e infección/inflamación. Especialmente útil en atención primaria.</p>
<h4>6.3 Índice de Toronto (Toronto Symptom Assessment)</h4>
<p>Escala validada para el dolor en procedimientos de cura. Permite objetivar y comunicar el dolor antes, durante y tras la cura.</p>
<h4>6.4 Documentación mínima en cada valoración</h4>
<ul><li>Localización exacta (diagrama corporal si es posible)</li><li>Dimensiones: longitud x anchura (cm²) ± profundidad (cm)</li><li>Tipo de tejido en el lecho: % granulación / % fibrina / % necrosis</li><li>Estado de los bordes: regulares, irregulares, socavados, rodados, epitelizando</li><li>Exudado: cantidad (escaso/moderado/abundante) + aspecto (seroso/serohemático/purulento)</li><li>Piel perilesional: íntegra, macerada, eccema, hiperpigmentación</li><li>Signos locales de infección (NERDS): No healing, Exudate, Red friable, Debris, Smell</li><li>Signos sistémicos de infección (STONEES): Size, Temperature, Os, New satellite, Erythema, Exudate, Smell</li><li>Dolor: EVA / NRS antes y durante la cura</li><li>Apósito utilizado y frecuencia de cambio</li></ul>
<div class="callout truco"><span class="lbl">Fotografía clínica estandarizada</span><p>Incluir siempre regla métrica, misma distancia y ángulo. La imagen es parte de la historia clínica. En Atenea: adjuntar en la entrada de curas.</p></div>
<p><em>Elaborado para uso docente en prácticas de Enfermería · Centro de Salud Palma Norte</em></p>
<p><em>Referencia clínica: Dra. Elena Conde Montero — Dermatología y Heridas, HU Infanta Leonor, Madrid</em></p>
` },
  { id:"pie-1", titulo:"Pie diabético · Por qué explorar y con qué material", min:4, html:`
<h3>Introducción: por qué explorar el pie diabético</h3>
<p>El pie diabético es una de las complicaciones más graves y prevalentes de la diabetes mellitus. La exploración sistemática del pie en cada contacto con el paciente diabético es una de las intervenciones enfermeras de mayor impacto en la prevención de amputaciones.</p>
<p><strong>Dato clave:</strong> el 85% de las amputaciones en el pie diabético están precedidas por una úlcera, y la mayoría de estas úlceras son prevenibles con una detección y actuación precoz.</p>
<h4>Triada fisiopatológica</h4>
<div class="tbl-scroll"><table><tr><th>Factor</th><th>Papel en el pie diabético</th></tr><tr><td><strong>Neuropatía periférica</strong></td><td>Afecta a fibras sensitivas (pérdida de sensación protectora), motoras (deformidades) y autonómicas (piel seca, anhidrosis). Presente en el 50% de pacientes con DM de > 10 años de evolución.</td></tr><tr><td><strong>Enfermedad arterial periférica (EAP)</strong></td><td>Arteriosclerosis acelerada que compromete la perfusión distal. Dificulta la cicatrización y favorece la infección. Presente en 20-40% de pacientes con pie diabético.</td></tr><tr><td><strong>Infección</strong></td><td>La inmunosupresión relativa de la DM, la neuropatía y la isquemia crean el terreno para infecciones graves, a menudo polimicrobianas y con biofilm.</td></tr></table></div>
<div class="callout truco"><span class="lbl">Objetivo de la exploración del pie diabético en AP</span><p>→ Estratificar el riesgo de ulceración y amputación.</p><p>→ Detectar signos precoces de neuropatía o vasculopatía antes de que aparezca la úlcera.</p><p>→ Planificar la frecuencia de revisión y las intervenciones preventivas.</p><p>→ Registrar de forma sistemática para hacer seguimiento evolutivo.</p><p>→ Identificar señales de alarma que requieren derivación urgente.</p></div>
<h3>Material necesario para la exploración</h3>
<p>La exploración del pie diabético no requiere equipamiento costoso. Todo el material necesario debe estar disponible en una consulta de enfermería de atención primaria.</p>
<div class="tbl-scroll"><table><tr><th>Material</th><th>Para qué se usa</th></tr><tr><td><strong>Monofilamento de Semmes-Weinstein (10 g)</strong></td><td>Evaluación de la sensibilidad protectora. Es el instrumento más validado para detectar neuropatía periférica.</td></tr><tr><td><strong>Diapasón de 128 Hz</strong></td><td>Evaluación de la sensibilidad vibratoria. Complementa al monofilamento.</td></tr><tr><td><strong>Martillo de reflejos</strong></td><td>Evaluación del reflejo aquíleo y rotuliano.</td></tr><tr><td><strong>Doppler portátil de ultrasonidos</strong></td><td>Imprescindible para el cálculo del Índice Tobillo-Brazo (ITB).</td></tr><tr><td><strong>Esfigmomanómetro</strong></td><td>Necesario para la medición de la presión arterial en brazo y tobillo (ITB).</td></tr><tr><td><strong>Algodón / torunda</strong></td><td>Evaluación de la sensibilidad superficial al tacto ligero.</td></tr><tr><td><strong>Objeto romo y objeto punzante</strong></td><td>Evaluación de la discriminación entre presión y pinchazo.</td></tr><tr><td><strong>Cinta métrica o regla</strong></td><td>Medición de úlceras si las hay.</td></tr><tr><td><strong>Linterna o fuente de luz directa</strong></td><td>Inspección de espacios interdigitales y planta.</td></tr><tr><td><strong>Guantes no estériles</strong></td><td>Protección durante la exploración.</td></tr><tr><td><strong>Hoja de registro estructurada / plantilla de pie</strong></td><td>Documentación sistemática de los hallazgos.</td></tr></table></div>
<div class="callout truco"><span class="lbl">Nota para la estudiante</span><p>El monofilamento se calibra por el fabricante. Antes de usarlo, comprueba que al presionarlo contra la palma de tu mano percibes la sensación. Si el monofilamento ya no se curva uniformemente o está deteriorado, hay que reemplazarlo: un monofilamento gastado subestima el déficit sensitivo.</p><p>El Doppler portátil no es opcional: sin él no se puede calcular el ITB y no se puede valorar correctamente la función arterial.</p></div>
` },
  { id:"pie-2", titulo:"Pie diabético · Exploración vascular", min:5, html:`
<h3>Exploración vascular</h3>
<p>La exploración vascular busca detectar enfermedad arterial periférica (EAP) que comprometa la perfusión del pie. Incluye la palpación de pulsos, el cálculo del ITB y la valoración del tiempo de relleno capilar.</p>
<h4>3.1 Palpación de pulsos</h4>
<p>Se exploran sistemáticamente tres pulsos en cada extremidad inferior. La palpación se realiza con los dedos índice y medio, nunca con el pulgar (el pulso propio del explorador puede confundirse).</p>
<div class="tbl-scroll"><table><tr><th>Pulso</th><th>Localización y técnica</th><th>Significado clínico</th></tr><tr><td>Pulso femoral</td><td>Triángulo de Scarpa (cara anteromedial del muslo, justo por debajo del ligamento inguinal, a mitad de camino entre la espina ilíaca anterosuperior y la sínfisis del pubis).</td><td>El más proximal. Su ausencia indica obstrucción aortoilíaca.</td></tr><tr><td>Pulso poplíteo</td><td>Fosa poplítea, con la rodilla ligeramente flexionada. Presionar profundo con ambas manos entrelazadas por la cara posterior de la rodilla.</td><td>Más difícil de palpar. Su ausencia indica obstrucción femoropoplítea.</td></tr><tr><td>Pulso pedio (arteria dorsal del pie)</td><td>Dorso del pie, lateral al tendón extensor del primer dedo, entre el primero y segundo metatarsianos.</td><td>Ausente en 8-10% de población sana (variante anatómica). Valorar siempre en contexto.</td></tr><tr><td>Pulso tibial posterior</td><td>Cara posterior del maléolo interno (tibial), en el surco entre el maléolo y el tendón de Aquiles.</td><td>Más fiable que el pedio para detectar EAP. Su ausencia es más significativa.</td></tr></table></div>
<div class="tbl-scroll"><table><tr><th>Graduación</th><th>Interpretación</th></tr><tr><td><strong>+++ (lleno, fuerte)</strong></td><td>Pulso normal, buena perfusión.</td></tr><tr><td><strong>++ (presente, normal)</strong></td><td>Perfusión adecuada.</td></tr><tr><td><strong>+ (débil, filiforme)</strong></td><td>Perfusión disminuida, posible EAP. Completar con ITB.</td></tr><tr><td><strong>— (ausente)</strong></td><td>Alta sospecha de obstrucción arterial. ITB imprescindible. Valorar derivación vascular.</td></tr></table></div>
<div class="callout truco"><span class="lbl">Punto de atención clínica</span><p>La ausencia bilateral de pulsos pedios y tibiales posteriores, especialmente asociada a piel fría, palidez o cianosis distal, indica isquemia crítica y requiere derivación urgente al servicio de cirugía vascular.</p><p>La presencia de pulsos no descarta EAP significativa: en pacientes con calcificación arterial (frecuente en DM), los pulsos pueden parecer presentes aunque el flujo esté comprometido. El ITB es imprescindible.</p></div>
<h4>3.2 Índice Tobillo-Brazo (ITB)</h4>
<p>El ITB es el cociente entre la presión arterial sistólica en el tobillo y la presión arterial sistólica en el brazo. Es la prueba de referencia no invasiva para el diagnóstico de EAP en atención primaria.</p>
<h4><em>Material necesario</em></h4>
<ul><li>Esfigmomanómetro con manguito estándar</li><li>Doppler portátil de ultrasonidos con sonda de 8 MHz</li><li>Gel conductor</li></ul>
<h4><em>Técnica paso a paso</em></h4>
<h4>Paso 1 — Preparación del paciente:</h4>
<ul><li>El paciente debe estar en decúbito supino durante al menos 10 minutos antes de la medición.</li><li>Temperatura ambiente confortable (el frío produce vasoconstricción que falsea el resultado).</li><li>No haber fumado, tomado cafeína ni hecho ejercicio en la hora previa.</li></ul>
<h4>Paso 2 — Medición de la presión en los brazos:</h4>
<ul><li>Colocar el manguito en ambos brazos (parte superior del brazo, borde inferior a 2-3 cm del pliegue del codo).</li><li>Aplicar gel conductor sobre la arteria braquial en el pliegue del codo.</li><li>Colocar la sonda Doppler a 45-60° sobre la arteria braquial.</li><li>Inflar el manguito hasta 20-30 mmHg por encima de la desaparición del sonido Doppler.</li><li>Desinflar lentamente (2-3 mmHg/segundo) y registrar la presión a la que reaparece el sonido.</li><li>Registrar el valor más alto de los dos brazos. Este es el denominador del ITB.</li></ul>
<h4>Paso 3 — Medición de la presión en los tobillos:</h4>
<ul><li>Colocar el manguito justo por encima del maléolo (tobillo), en cada pierna.</li><li>Localizar con el Doppler la arteria tibial posterior (posterior al maléolo interno) y la arteria dorsal del pie.</li><li>Repetir la misma técnica de insuflación/desinsuflación para cada arteria.</li><li>Registrar el valor más alto de las dos arterias del mismo tobillo. Este es el numerador del ITB de ese lado.</li></ul>
<h4>Paso 4 — Cálculo:</h4>
<p>ITB derecho = Presión sistólica más alta tobillo derecho ÷ Presión sistólica más alta de los brazos</p>
<p>ITB izquierdo = Presión sistólica más alta tobillo izquierdo ÷ Presión sistólica más alta de los brazos</p>
<h4><em>Interpretación del ITB</em></h4>
<div class="tbl-scroll"><table><tr><th>ITB</th><th>Interpretación y conducta</th></tr><tr><td><strong>> 1,30</strong></td><td>Arterias calcificadas (no compresibles). Resultado NO fiable. Frecuente en DM e IRC. Solicitar índice dedo-brazo o presión en el dedo del pie.</td></tr><tr><td><strong>0,91 – 1,30</strong></td><td>Normal. No hay obstrucción arterial significativa.</td></tr><tr><td><strong>0,71 – 0,90</strong></td><td>EAP leve. El paciente puede estar asintomático o con claudicación leve. Seguimiento y control de factores de riesgo cardiovascular.</td></tr><tr><td><strong>0,41 – 0,70</strong></td><td>EAP moderada. Claudicación intermitente habitual. Valorar derivación a cirugía vascular.</td></tr><tr><td><strong>≤ 0,40</strong></td><td>EAP grave / isquemia crítica. Derivación urgente a cirugía vascular. CONTRAINDICADA la compresión.</td></tr></table></div>
<div class="callout truco"><p><strong>El ITB en el paciente diabético: la trampa de la calcificación</strong></p><p>La calcificación de la capa media arterial (mediocalcinosis de Mönckeberg) es muy frecuente en la DM. Hace que las arterias sean rígidas e incompresibles, lo que eleva falsamente la presión en el tobillo → ITB > 1,3 o incluso > 1,5.</p><p>Ante un ITB > 1,3 en paciente diabético, la alternativa es el Índice Dedo-Brazo (IDB): se mide la presión en el primer dedo del pie con un pequeño manguito digital. IDB normal ≥ 0,70.</p><p>También se puede solicitar ecografía Doppler arterial o presión transcutánea de oxígeno (TcPO2) si hay sospecha de isquemia a pesar de ITB falsamente elevado.</p></div>
<h4>3.3 Tiempo de relleno capilar (TRC)</h4>
<p>Es una prueba rápida y sencilla que complementa la palpación de pulsos. Valora la perfusión capilar distal.</p>
<h4><em>Técnica</em></h4>
<ul><li>Con el paciente en decúbito supino, elevar el pie ligeramente por encima del nivel del corazón.</li><li>Presionar firmemente durante 5 segundos la pulpa del primer dedo del pie hasta producir palidez.</li><li>Soltar la presión y medir el tiempo hasta que el color rosado reaparece completamente.</li></ul>
<div class="tbl-scroll"><table><tr><th>Tiempo de relleno</th><th>Interpretación</th></tr><tr><td><strong>< 2 segundos</strong></td><td>Normal. Perfusión capilar adecuada.</td></tr><tr><td><strong>2-3 segundos</strong></td><td>Límite. Repetir y correlacionar con otros hallazgos.</td></tr><tr><td><strong>> 3 segundos</strong></td><td>Patológico. Sugiere hipoperfusión distal. Completar estudio vascular.</td></tr><tr><td><strong>> 5-6 segundos</strong></td><td>Isquemia significativa. Alta sospecha de EAP grave.</td></tr></table></div>
<p><strong>Limitaciones:</strong> el TRC puede estar alterado por hipotermia, anemia, o en exploradores con presión insuficiente. Debe interpretarse siempre junto con el resto de la exploración vascular.</p>
` },
  { id:"pie-3", titulo:"Pie diabético · Exploración neurológica", min:5, html:`
<h3>Exploración neurológica</h3>
<p>La neuropatía periférica diabética afecta a fibras sensitivas, motoras y autonómicas. Su detección precoz es clave porque la pérdida de la sensación protectora es el principal factor de riesgo de ulceración.</p>
<h4>4.1 Monofilamento de Semmes-Weinstein (10 g)</h4>
<p>Es la prueba más importante y validada para detectar pérdida de sensación protectora. Un resultado anormal multiplica por 7 el riesgo de ulceración.</p>
<h4><em>Técnica paso a paso</em></h4>
<ul><li>Explicar al paciente en qué consiste la prueba: "Voy a tocar tu pie con este instrumento. Cuando lo sientas, di 'sí'. Cuando no lo sientas, no digas nada."</li><li>El paciente debe tener los ojos cerrados o desviados para no ver dónde se aplica el monofilamento.</li><li>Demostrar primero la sensación aplicando el monofilamento en la mano o el antebrazo del paciente.</li><li>Aplicar el monofilamento perpendicularmente a la piel, con presión suficiente para que se curve ligeramente (en forma de C). Este momento de curvatura corresponde exactamente a 10 gramos de presión.</li><li>Mantener la presión durante aproximadamente 1-2 segundos. No hacer movimientos de deslizamiento.</li><li>Levantar el monofilamento y preguntar: "¿Lo has notado?" Registrar si la respuesta es correcta.</li><li>Aplicar en los 9 puntos estándar según el esquema de exploración.</li><li>Variar el ritmo de aplicación (incluir a veces una aplicación falsa, sin tocar, para comprobar que el paciente no responde al azar).</li><li>Evitar aplicar sobre zonas de callosidad, úlcera activa, cicatriz o necrosis.</li></ul>
<h4><em>Puntos de exploración estándar (9 puntos)</em></h4>
<div class="tbl-scroll"><table><tr><th>Punto</th><th>Localización</th><th>Nota</th></tr><tr><td>1</td><td>Pulpa del primer dedo (hallux)</td><td>Zona de máxima presión y frecuente ulceración.</td></tr><tr><td>2</td><td>Pulpa del tercer dedo</td><td></td></tr><tr><td>3</td><td>Pulpa del quinto dedo</td><td></td></tr><tr><td>4</td><td>Primera cabeza metatarsiana (cara plantar)</td><td>Zona de mayor presión en la marcha.</td></tr><tr><td>5</td><td>Tercera cabeza metatarsiana (cara plantar)</td><td></td></tr><tr><td>6</td><td>Quinta cabeza metatarsiana (cara plantar)</td><td></td></tr><tr><td>7</td><td>Arco plantar medial</td><td></td></tr><tr><td>8</td><td>Calcáneo (zona central plantar)</td><td>Frecuente ulceración en pacientes encamados.</td></tr><tr><td>9</td><td>Dorso del pie (espacio 1.º-2.º dedo)</td><td>Única zona dorsal incluida en el protocolo estándar.</td></tr></table></div>
<h4><em>Interpretación</em></h4>
<div class="tbl-scroll"><table><tr><th>Resultado</th><th>Interpretación y conducta</th></tr><tr><td><strong>8-9 puntos correctos</strong></td><td>Normal. Sensación protectora conservada.</td></tr><tr><td><strong>4-7 puntos correctos</strong></td><td>Déficit sensitivo moderado. Riesgo elevado de ulceración. Intensificar prevención.</td></tr><tr><td><strong>0-3 puntos correctos</strong></td><td>Pérdida grave de sensación protectora. Riesgo muy alto. Educación intensiva, plantillas, revisión frecuente.</td></tr></table></div>
<div class="callout truco"><span class="lbl">Errores frecuentes en la aplicación del monofilamento</span><p>✗ Aplicarlo sobre callos o hiperqueratosis: la piel engrosada falsea el resultado (falso negativo).</p><p>✗ No dejar que se curve: si no hay curvatura, no se están aplicando los 10 g.</p><p>✗ Aplicarlo siempre en el mismo orden y ritmo: el paciente aprende el patrón y responde condicionado.</p><p>✗ Olvidar las aplicaciones falsas: sin ellas no se puede detectar al paciente que responde por azar.</p><p>✗ No registrar punto por punto: "explorado con monofilamento: normal" no es un registro válido.</p></div>
<h4>4.2 Diapasón de 128 Hz — Sensibilidad vibratoria</h4>
<p>Evalúa la sensibilidad vibratoria, que se pierde precozmente en la neuropatía periférica. Se afectan primero las fibras gruesas mielinizadas que conducen la sensibilidad vibratoria y propioceptiva.</p>
<h4><em>Técnica paso a paso</em></h4>
<ul><li>Golpear el diapasón con suavidad contra la palma de la mano para que vibre. No golpearlo contra superficies duras.</li><li>Colocar el mango del diapasón (no las ramas) sobre la prominencia ósea a explorar, perpendicular a la piel, con presión constante.</li><li>Preguntar primero: "¿Sientes la vibración?" y después: "¿Cuándo para de vibrar?"</li><li>Amortiguar las ramas con los dedos y preguntar si el paciente nota el cambio.</li><li>El paciente debe tener los ojos cerrados.</li></ul>
<h4><em>Puntos de exploración</em></h4>
<ul><li>Primera elección: maléolo interno (tobillo). Es el punto estándar más utilizado.</li><li>Si normal en tobillo: explorar en la cabeza del primer metatarsiano.</li><li>Si anormal en tobillo: ascender para determinar el nivel de la lesión (rodilla, cresta ilíaca).</li></ul>
<h4><em>Interpretación</em></h4>
<div class="tbl-scroll"><table><tr><th>Resultado</th><th>Interpretación</th></tr><tr><td><strong>Siente la vibración y detecta cuándo para</strong></td><td>Normal. Fibras gruesas mielinizadas intactas.</td></tr><tr><td><strong>Siente la vibración pero no detecta cuándo para</strong></td><td>Déficit leve. Repetir y correlacionar.</td></tr><tr><td><strong>No siente la vibración</strong></td><td>Neuropatía periférica. Combinar con resultado del monofilamento para estratificar riesgo.</td></tr></table></div>
<p><strong>Test de Rydel-Seiffer:</strong> es la versión cuantificada del diapasón, con una escala graduada de 0-8 en el mango. Un resultado < 4/8 en el maléolo tibial es patológico y equivale a pérdida de sensación protectora.</p>
<h4>4.3 Sensibilidad al tacto superficial</h4>
<h4><em>Técnica</em></h4>
<ul><li>Utilizar una torunda de algodón o un pincel fino.</li><li>Rozar suavemente la piel del dorso del pie y la planta, con el paciente con los ojos cerrados.</li><li>El paciente debe indicar cuándo y dónde siente el toque.</li><li>Comparar simétricamente ambos pies y comparar con zonas proximales (pierna, muslo).</li></ul>
<h4>4.4 Sensibilidad al dolor superficial (discriminación romo/punzante)</h4>
<h4><em>Técnica</em></h4>
<ul><li>Utilizar un objeto de punta roma y otro de punta punzante (no utilizar agujas hipodérmicas por riesgo de sangrado e infección).</li><li>Aplicar alternativamente en la planta y el dorso del pie, con el paciente con los ojos cerrados.</li><li>Pedir al paciente que distinga entre "presión" y "pinchazo".</li><li>La incapacidad para distinguir indica afectación de fibras delgadas amielínicas (neuropatía de fibra fina).</li></ul>
<h4>4.5 Reflejos osteotendinosos</h4>
<p>La disminución o ausencia del reflejo aquíleo es uno de los signos más precoces y sensibles de neuropatía periférica diabética.</p>
<h4><em>Reflejo aquíleo</em></h4>
<ul><li>Paciente en sedestación con el pie relajado y el tobillo en ligera flexión dorsal.</li><li>Golpear con el martillo de reflejos directamente sobre el tendón de Aquiles, justo por encima de su inserción en el calcáneo.</li><li>La respuesta normal es la flexión plantar del pie.</li><li>Si no aparece respuesta: reforzar con la maniobra de Jendrassik (el paciente entrelaza las manos y tira con fuerza hacia afuera mientras se explora el reflejo).</li></ul>
<div class="tbl-scroll"><table><tr><th>Resultado</th><th>Interpretación</th></tr><tr><td><strong>+++</strong></td><td>Exaltado (raramente patológico en este contexto).</td></tr><tr><td><strong>++</strong></td><td>Normal.</td></tr><tr><td><strong>+</strong></td><td>Disminuido. Posible inicio de neuropatía. Correlacionar con el resto de la exploración.</td></tr><tr><td><strong>—</strong></td><td>Ausente. Signo de neuropatía periférica establecida.</td></tr></table></div>
<h4>4.6 Propriocepción</h4>
<h4><em>Técnica</em></h4>
<ul><li>Con el paciente con los ojos cerrados, sostener lateralmente el primer dedo del pie (sin presionar la pulpa ni la uña, para no dar pistas táctiles).</li><li>Mover el dedo hacia arriba o hacia abajo y preguntar al paciente en qué posición está.</li><li>La incapacidad para identificar la posición indica afectación de la propriocepción (fibras gruesas mielinizadas).</li></ul>
` },
  { id:"pie-4", titulo:"Pie diabético · Exploración dermatológica y musculoesquelética", min:5, html:`
<h3>Exploración dermatológica</h3>
<p>La inspección cuidadosa de la piel es una parte fundamental de la exploración del pie diabético. La neuropatía autonómica, la vasculopatía y la inmunosupresión relativa dejan huellas visibles en la piel y los anejos.</p>
<h4>5.1 Temperatura y color de la piel</h4>
<div class="tbl-scroll"><table><tr><th>Hallazgo</th><th>Significado clínico</th></tr><tr><td><strong>Piel fría y pálida</strong></td><td>Isquemia: vasoconstricción, reducción del flujo arterial.</td></tr><tr><td><strong>Piel fría y cianótica</strong></td><td>Isquemia grave. Valorar junto con ausencia de pulsos y TRC alargado.</td></tr><tr><td><strong>Piel caliente, eritematosa</strong></td><td>Infección activa o inflamación. Descartar celulitis, artropatía de Charcot activa.</td></tr><tr><td><strong>Piel caliente + deformidad aguda (sin úlcera)</strong></td><td>Artropatía de Charcot activa → derivación urgente al traumatólogo/podólogo especializado.</td></tr><tr><td><strong>Piel seca, fina y brillante</strong></td><td>Neuropatía autonómica (pérdida de sudoración) + atrofia cutánea por isquemia.</td></tr><tr><td><strong>Hiperpigmentación</strong></td><td>Depósito de hemosiderina por insuficiencia venosa concomitante.</td></tr></table></div>
<h4>5.2 Hidratación y trofismo</h4>
<ul><li>Valorar el grado de hidratación de la piel: la neuropatía autonómica produce anhidrosis (ausencia de sudoración), lo que genera piel muy seca con tendencia a las fisuras.</li><li>Las fisuras en el talón son una puerta de entrada frecuente para infecciones, especialmente en pacientes con EAP asociada.</li><li>Palpar la elasticidad y el grosor de la piel: la piel atrófica, fina y poco elástica indica compromiso vascular crónico.</li></ul>
<h4>5.3 Lesiones a identificar</h4>
<div class="tbl-scroll"><table><tr><th>Lesión</th><th>Descripción y significado</th></tr><tr><td><strong>Hiperqueratosis / callos (helomas)</strong></td><td>Acúmulo de piel muerta por presión excesiva. Indican un punto de hiperpresión que puede evolucionar a úlcera. Requieren cuidado podológico y valoración del calzado.</td></tr><tr><td><strong>Fisuras</strong></td><td>Especialmente en talón y espacios interdigitales. Puerta de entrada para infecciones bacterianas y micóticas.</td></tr><tr><td><strong>Ampollas</strong></td><td>Por traumatismo, rozadura o calzado inadecuado. No pinchar sin valorar el contexto (pueden ser isquémicas o hemorrágicas).</td></tr><tr><td><strong>Maceración interdigital</strong></td><td>Piel blanquecina, blanda y húmeda entre los dedos. Favorece infección por hongos (tinea pedis) y bacterias. Explorar siempre los espacios interdigitales.</td></tr><tr><td><strong>Eritema</strong></td><td>Localizado: puede indicar inicio de celulitis. Difuso: valorar alergia a material del calzado o medias.</td></tr><tr><td><strong>Úlceras</strong></td><td>Describir localización, dimensiones, profundidad, tipo de tejido, exudado, bordes y estado perilesional.</td></tr><tr><td><strong>Necrosis</strong></td><td>Escara seca (isquémica) o tejido húmedo negruzco (gangrena húmeda, urgencia).</td></tr></table></div>
<h4>5.4 Exploración de los anejos</h4>
<h4><em>Uñas</em></h4>
<ul><li>Onicomicosis: engrosamiento, coloración amarillo-marrón, distrofia ungueal. Favorece la ulceración subungueal.</li><li>Onicocriptosis (uña incarnada): bordes de la uña penetran en el tejido blando lateral. Frecuente causa de infección.</li><li>Hipertrofia ungueal: uñas muy engrosadas y duras. Difíciles de cortar por el propio paciente → riesgo de lesión iatrogénica.</li><li>Subungual: inspeccionar bajo la uña si está engrosada o levantada, buscando úlceras subungueales (pueden pasar desapercibidas).</li></ul>
<h4><em>Vello</em></h4>
<ul><li>La pérdida de vello en el dorso del pie y la cara anterior de la pierna es un signo de insuficiencia vascular crónica.</li></ul>
<h4><em>Sudoración</em></h4>
<ul><li>La piel seca, sin brillo, que no suda, es un signo clásico de neuropatía autonómica.</li></ul>
<h4>5.5 Exploración sistemática de los espacios interdigitales</h4>
<p>Es uno de los pasos más frecuentemente omitidos y más importantes. La mayoría de las infecciones del pie diabético comienzan en los espacios interdigitales.</p>
<ul><li>Separar suavemente cada dedo del siguiente y examinar toda la superficie interdigital.</li><li>Buscar: maceración, eritema, fisuras, vesículas (tinea), úlceras ocultas, secreción.</li><li>Registrar hallazgo en cada espacio (1-2, 2-3, 3-4, 4-5).</li></ul>
<h3>Exploración musculoesquelética</h3>
<p>La neuropatía motora produce atrofia de los músculos intrínsecos del pie, lo que genera deformidades estructurales que crean puntos de hiperpresión y aumentan el riesgo de ulceración.</p>
<h4>6.1 Deformidades a identificar</h4>
<div class="tbl-scroll"><table><tr><th>Deformidad</th><th>Descripción y riesgo</th></tr><tr><td><strong>Dedos en martillo</strong></td><td>Flexión permanente de la articulación interfalángica proximal. Crea roce en el dorso del dedo con el calzado y en la punta con el suelo.</td></tr><tr><td><strong>Dedos en garra</strong></td><td>Flexión de ambas interfalángicas (proximal y distal) con extensión de la MTF. Hiperpresión en cabezas metatarsianas y en la pulpa de los dedos.</td></tr><tr><td><strong>Dedos en maza</strong></td><td>Solo la interfalángica distal en flexión. Hiperpresión en la punta del dedo.</td></tr><tr><td><strong>Hallux valgus</strong></td><td>Desviación lateral del primer dedo. Crea prominencia medial de la primera MTF propensa a úlcera.</td></tr><tr><td><strong>Pie cavo</strong></td><td>Arco plantar muy elevado. Hiperpresión en talón y cabezas metatarsianas anteriores.</td></tr><tr><td><strong>Pie plano</strong></td><td>Arco plantar aplanado. Distribución anómala de la presión. Frecuente tras artropatía de Charcot.</td></tr><tr><td><strong>Artropatía de Charcot</strong></td><td>Destrucción progresiva de las articulaciones del pie por la neuropatía. Fase activa: pie muy caliente, eritematoso y edematoso SIN úlcera. Urgencia. Fase crónica: pie deformado («pie en balancín»).</td></tr></table></div>
<h4>6.2 Limitación de la movilidad articular</h4>
<p>La glucosilación del colágeno en la DM produce rigidez articular. La limitación de la dorsiflexión del tobillo aumenta la presión plantar durante la marcha.</p>
<h4><em>Test de dorsiflexión del tobillo</em></h4>
<ul><li>Pedir al paciente que se coloque con el pie a explorar sobre una superficie plana y flexione la rodilla hacia adelante intentando que no se levante el talón.</li><li>Normal: el paciente puede desplazar la rodilla al menos 5 cm por delante de los dedos del pie.</li><li>Limitado: si el talón se levanta antes de los 5 cm, existe limitación de la dorsiflexión → mayor riesgo de hiperpresión en el antepié.</li></ul>
<h4>6.3 Estudio de la marcha y distribución de presiones</h4>
<p>Aunque el estudio baropodométrico completo pertenece al ámbito del podólogo especializado, en AP se puede hacer una valoración básica:</p>
<ul><li>Observar la marcha del paciente al entrar y salir de la consulta.</li><li>Inspeccionar las zonas de desgaste de las suelas del calzado: indican los puntos de mayor presión.</li><li>Buscar callosidades plantares: su localización indica el mapa de hiperpresiones del pie del paciente.</li></ul>
` },
  { id:"pie-5", titulo:"Pie diabético · Calzado, registro y clasificación del riesgo", min:4, html:`
<h3>Valoración del calzado</h3>
<p>El calzado inadecuado es el principal factor externo de ulceración en el pie diabético. La valoración del calzado debe ser sistemática en cada visita.</p>
<h4>7.1 Valoración del calzado actual</h4>
<ul><li>Pedir al paciente que traiga el calzado que usa habitualmente.</li><li>Inspeccionar el interior: zonas de roce, cuerpos extraños (piedras, costuras prominentes, objetos olvidados).</li><li>Inspeccionar la suela: patrón de desgaste (indica puntos de hiperpresión y alteraciones de la marcha).</li><li>Medir la longitud interna del zapato y comparar con la del pie: debe haber al menos 1 cm de espacio al final.</li><li>Comprobar la anchura: el pie no debe presionar lateralmente las paredes del zapato.</li><li>Comprobar el contrafuerte (parte trasera rígida que sujeta el talón): debe ser firme.</li><li>Valorar la puntera: debe ser amplia, redondeada y sin costuras internas que presionen los dedos.</li></ul>
<h4>7.2 Características del calzado adecuado para el pie diabético</h4>
<div class="tbl-scroll"><table><tr><th>Característica</th><th>Criterio</th></tr><tr><td><strong>Talla</strong></td><td>Al menos 1 cm más largo que el pie más largo. Comprar calzado al final del día (el pie está más hinchado).</td></tr><tr><td><strong>Anchura</strong></td><td>Suficiente para no comprimir ningún dedo. Ancho en la puntera.</td></tr><tr><td><strong>Puntera</strong></td><td>Redondeada o cuadrada, alta, sin costuras internas, sin refuerzo rígido anterior.</td></tr><tr><td><strong>Material exterior</strong></td><td>Cuero natural o materiales transpirables. Evitar plásticos y materiales sintéticos que no transpiren.</td></tr><tr><td><strong>Interior</strong></td><td>Sin costuras internas prominentes. Plantilla extraíble para sustituirla por plantilla ortopédica si es necesario.</td></tr><tr><td><strong>Suela</strong></td><td>Gruesa (amortiguación), antideslizante, ligeramente rígida. Tacón bajo (≤ 3-4 cm).</td></tr><tr><td><strong>Cierre</strong></td><td>Con velcro o cordones que permitan ajustar el volumen. Evitar calzado sin cierre (chancletas, zueco sin correa posterior).</td></tr><tr><td><strong>Calzado ortopédico</strong></td><td>Indicado cuando existen deformidades, amputaciones previas o úlceras recurrentes. Prescripción especializada.</td></tr></table></div>
<div class="callout truco"><span class="lbl">Mensaje educativo clave sobre el calzado</span><p>"Nunca estrene zapatos sin graduarlos poco a poco. El pie diabético no siente el daño hasta que ya ha ocurrido."</p><p>"Inspeccione siempre el interior del zapato antes de ponérselo: un objeto pequeño que usted no siente puede causar una úlcera grave en pocas horas."</p><p>"El calzado apropiado no es un complemento estético, es parte del tratamiento."</p></div>
<h3>Registro y clasificación del riesgo</h3>
<p>Después de la exploración completa, los hallazgos deben registrarse de forma estructurada y el paciente debe clasificarse según su nivel de riesgo para establecer la frecuencia de revisión.</p>
<h4>8.1 Clasificación del riesgo de pie diabético (IWGDF 2023)</h4>
<div class="tbl-scroll"><table><tr><th>Categoría</th><th>Criterio principal</th><th>Criterio adicional</th><th>Revisión</th></tr><tr><td>0 — Muy bajo</td><td>Sin neuropatía, sin EAP.</td><td>Sin deformidades ni otros factores.</td><td>Anual</td></tr><tr><td>1 — Bajo</td><td>Neuropatía O EAP (sin ambas combinadas).</td><td>Sin úlcera previa ni deformidad significativa.</td><td>Cada 6-12 meses</td></tr><tr><td>2 — Moderado</td><td>Neuropatía + EAP, O neuropatía + deformidad, O EAP + deformidad.</td><td>Sin úlcera previa.</td><td>Cada 3-6 meses</td></tr><tr><td>3 — Alto</td><td>Úlcera previa o amputación previa (cualquier nivel).</td><td>O diálisis renal.</td><td>Cada 1-3 meses</td></tr></table></div>
<h4>8.2 Registro mínimo en cada valoración</h4>
<div class="tbl-scroll"><table><tr><th>Ítem</th><th>Cómo registrarlo</th></tr><tr><td><strong>Pulsos</strong></td><td>Femoral, poplíteo, pedio, tibial posterior (bilateralmente). Graduación: +++/++/+/—</td></tr><tr><td><strong>ITB</strong></td><td>Valor numérico en cada pierna. Fecha de la medición.</td></tr><tr><td><strong>TRC</strong></td><td>Segundos. Pie derecho e izquierdo.</td></tr><tr><td><strong>Monofilamento</strong></td><td>Puntuación por puntos (ej. 7/9 PI, 9/9 PD). Puntos fallidos especificados.</td></tr><tr><td><strong>Diapasón</strong></td><td>Normal/disminuido/ausente. Localización.</td></tr><tr><td><strong>Reflejo aquíleo</strong></td><td>Presente/disminuido/ausente (bilateral).</td></tr><tr><td><strong>Inspección cutánea</strong></td><td>Hallazgos por zonas: dorso, planta, talón, dedos, espacios interdigitales, uñas.</td></tr><tr><td><strong>Deformidades</strong></td><td>Descripción de las presentes.</td></tr><tr><td><strong>Calzado</strong></td><td>Adecuado/inadecuado. Observaciones.</td></tr><tr><td><strong>Educación</strong></td><td>Temas trabajados en la visita.</td></tr><tr><td><strong>Categoría de riesgo</strong></td><td>0 / 1 / 2 / 3 (IWGDF). Frecuencia de revisión establecida.</td></tr><tr><td><strong>Derivaciones</strong></td><td>A podología, cirugía vascular, endocrinología, urgencias si procede.</td></tr></table></div>
<h4>8.3 Señales de alarma: cuándo derivar de urgencias</h4>
<div class="callout alerta"><span class="lbl">Derivación URGENTE (mismo día / urgencias hospitalarias)</span><p>→ Celulitis de > 2 cm alrededor de la lesión.</p><p>→ Crepitación a la palpación (gas en tejidos: infección por anaerobios).</p><p>→ Afectación articular o tendinosa visible.</p><p>→ Fiebre ≥ 38°C con lesión en el pie.</p><p>→ Glucemia muy descontrolada en contexto de infección del pie.</p><p>→ Úlcera Wagner ≥ 3 (osteomielitis, absceso, gangrena).</p><p>→ Pie de Charcot activo (pie muy caliente, eritematoso, edematoso, sin úlcera).</p><p>→ Isquemia crítica: ausencia de pulsos + dolor de reposo + palidez/cianosis.</p></div>
<div class="callout truco"><span class="lbl">Derivación PREFERENTE (días/semanas según protocolo)</span><p>→ Primera úlcera en paciente sin seguimiento especializado.</p><p>→ ITB < 0,6 sin estudio vascular previo.</p><p>→ Neuropatía grave (monofilamento < 4/9) sin seguimiento en podología.</p><p>→ Deformidad progresiva que dificulta el calzado.</p><p>→ Onicomicosis extensa o onicocriptosis recurrente.</p></div>
` },
  { id:"pie-6", titulo:"Pie diabético · Educación terapéutica", min:4, html:`
<h3>Educación terapéutica en el pie diabético</h3>
<p>La educación terapéutica es una intervención enfermera de primer orden en la prevención del pie diabético. El paciente y su cuidador principal son los protagonistas del cuidado diario.</p>
<p><strong>Principio fundamental:</strong> la información sola no cambia conductas. La educación debe ser personalizada, adaptada al nivel de comprensión del paciente, y reforzada en cada visita.</p>
<h4>9.1 Áreas de educación</h4>
<h4><em>Cuidado diario del pie</em></h4>
<ul><li>Inspección diaria de ambos pies, incluidos los espacios interdigitales y la planta (usar espejo si no llega, o pedir ayuda al cuidador).</li><li>Lavado diario con agua tibia (nunca caliente: la neuropatía impide percibir quemaduras). Comprobar la temperatura con el codo o termómetro.</li><li>Secado minucioso, especialmente entre los dedos: la humedad favorece infección.</li><li>Hidratación diaria con crema emoliente, sin aplicar entre los dedos (favorece maceración).</li><li>Corte de uñas recto, sin apurar los laterales, con lima suave si las uñas son muy duras.</li><li>No aplicar calor directo (brasero, bolsa de agua caliente, manta eléctrica): riesgo de quemadura sin percepción.</li><li>No caminar descalzo, ni en casa.</li></ul>
<h4><em>Calzado y calcetines</em></h4>
<ul><li>Usar calcetines sin costuras, de fibras naturales (algodón o lana fina), sin elásticos que compriman.</li><li>Cambiar calcetines a diario.</li><li>Revisar el interior del calzado antes de ponérselo.</li><li>No estrenar calzado nuevo durante más de 1-2 horas al día las primeras semanas.</li></ul>
<h4><em>Cuándo consultar sin demora</em></h4>
<div class="callout truco"><p><strong>El paciente debe acudir a la consulta de enfermería o a urgencias SI observa:</strong></p><p>→ Cualquier herida, ampolla, corte o úlcera, por pequeña que sea.</p><p>→ Zona roja, caliente o hinchada en el pie.</p><p>→ Cambio de color en algún dedo (palidez, cianosis, enrojecimiento).</p><p>→ Dolor nuevo en el pie (especialmente si no lo tenía antes: puede ser isquemia).</p><p>→ Sensación de calor intenso en el pie sin causa aparente (puede ser Charcot).</p><p>→ Olor anormal en el pie o en el calzado.</p></div>
<h4>9.2 Control metabólico y factores de riesgo asociados</h4>
<div class="tbl-scroll"><table><tr><th>Factor</th><th>Objetivo y relevancia</th></tr><tr><td><strong>HbA1c</strong></td><td>Objetivo individualizado (generalmente < 7-7,5%). El mal control glucémico enlentece la cicatrización e incrementa el riesgo de infección.</td></tr><tr><td><strong>Tabaco</strong></td><td>El tabaquismo es el principal factor modificable de EAP. Derivar siempre a programa de deshabituación.</td></tr><tr><td><strong>Tensión arterial</strong></td><td>Objetivo < 130/80 mmHg en diabético con EAP. La HTA acelera la arteriosclerosis.</td></tr><tr><td><strong>Lípidos</strong></td><td>LDL < 70 mg/dL si EAP establecida. Terapia con estatinas.</td></tr><tr><td><strong>Actividad física</strong></td><td>Ejercicio aeróbico adaptado mejora la perfusión distal y el control glucémico.</td></tr></table></div>
<p><em>Elaborado para uso docente · Centro de Salud Palma Norte · Madrid</em></p>
<p><em>Referencia clínica: Dra. Elena Conde Montero · HU Infanta Leonor, Madrid</em></p>
` }
  ]
});
