window.BLOQUES = window.BLOQUES || [];

window.BLOQUES.push({
  id: "cronicos",
  n: 7,
  tapon: "negro",
  color: "#33413C",
  titulo: "Crónicos",
  sub: "Hipertensión, diabetes tipo 2 y EPOC: los tres procesos que más veces vas a ver en la consulta programada.",
  semana: "Semana 5",
  temas: [
  { id:"hta-1", titulo:"HTA · Qué es y qué pide la Cartera de Servicios", min:4, html:`
<h3>Definición, epidemiología y clasificación</h3>
<p>La hipertensión arterial (HTA) es la elevación mantenida de la presión arterial sistólica (PAS) ≥ 140 mmHg y/o de la presión arterial diastólica (PAD) ≥ 90 mmHg, medida en condiciones adecuadas en al menos dos visitas diferentes.</p>
<p><strong>Dato de contexto SERMAS:</strong> la HTA afecta a aproximadamente el 33% de la población adulta española y es el principal factor de riesgo cardiovascular atendido en atención primaria. Es una de las actividades preventivas con mayor impacto potencial en la consulta de enfermería.</p>
<h4>Clasificación (ESC/ESH 2018, de referencia en SERMAS)</h4>
<div class="tbl-scroll"><table><tr><th>Categoría</th><th>Valores de presión arterial</th></tr><tr><td><strong>Óptima</strong></td><td>< 120 / < 80 mmHg</td></tr><tr><td><strong>Normal</strong></td><td>120-129 / 80-84 mmHg</td></tr><tr><td><strong>Normal-alta</strong></td><td>130-139 / 85-89 mmHg</td></tr><tr><td><strong>HTA grado 1</strong></td><td>140-159 / 90-99 mmHg</td></tr><tr><td><strong>HTA grado 2</strong></td><td>160-179 / 100-109 mmHg</td></tr><tr><td><strong>HTA grado 3</strong></td><td>≥ 180 / ≥ 110 mmHg</td></tr><tr><td><strong>HTA sistólica aislada</strong></td><td>PAS ≥ 140 con PAD < 90 mmHg (frecuente en mayores)</td></tr></table></div>
<h3>La HTA en la cartera de servicios SERMAS</h3>
<p>La Cartera de Servicios de Atención Primaria de la Comunidad de Madrid incluye la atención al paciente hipertenso como servicio específico (Servicio 310 — Atención a la persona hipertensa). Define las actividades mínimas que debe garantizar enfermería en cada contacto.</p>
<h4>Actividades incluidas en el Servicio 310</h4>
<div class="tbl-scroll"><table><tr><th>Actividad</th><th>Descripción</th></tr><tr><td><strong>Detección y diagnóstico</strong></td><td>Medición de TA en toda consulta de oportunidad. Confirmación diagnóstica según criterios.</td></tr><tr><td><strong>Registro en historia clínica</strong></td><td>Registro sistemático en Atenea: TA, peso, IMC, tabaco, analítica, ECG basal, SCORE cardiovascular.</td></tr><tr><td><strong>Valoración del riesgo CV</strong></td><td>Cálculo del riesgo cardiovascular (SCORE2 / SCORE2-OP) en cada paciente hipertenso.</td></tr><tr><td><strong>Educación para la salud</strong></td><td>Consejo sobre dieta, sal, alcohol, tabaco, ejercicio físico y adherencia terapéutica en cada visita.</td></tr><tr><td><strong>Control y seguimiento</strong></td><td>Visitas periódicas según control: cada 3-6 meses si no controlado, cada 6-12 meses si controlado.</td></tr><tr><td><strong>Detección de lesión de órgano diana</strong></td><td>Solicitud de analítica básica (creatinina, iones, glucosa, perfil lipídico, orina) y ECG anual.</td></tr></table></div>
<div class="callout verifica"><span class="lbl">Indicador de calidad SERMAS</span><p>El Contrato Programa establece como indicador de calidad el porcentaje de pacientes hipertensos con TA controlada (< 140/90 mmHg) registrada en el último año. Este indicador es responsabilidad compartida médico-enfermería y forma parte de la evaluación del centro.</p></div>
<div class="callout verifica"><span class="lbl">Actualización · Contrato Programa 2026</span><p>En 2026 el Contrato Programa de Centro actualiza las cifras de buen control de la HTA para su indicador, adecuándolas a las guías internacionales: <strong>PAS &lt;130 y PAD &lt;80 mmHg en menores de 80 años; PAS &lt;140 y PAD &lt;80 mmHg a partir de 80 años</strong>. En personas con cardiopatía isquémica o ictus, &lt;130/80. Ten en cuenta que las tablas de este tema reflejan las guías de referencia anteriores; el objetivo individual de cada paciente lo fija el médico y puede ser distinto del umbral del indicador.</p></div>
<h3>Papel de enfermería en el manejo de la HTA</h3>
<p>Enfermería tiene un papel protagonista en el manejo de la HTA en AP, con competencias propias reconocidas en la Cartera de Servicios SERMAS:</p>
<ul><li>Detección oportunista: medir la TA en toda visita a paciente adulto sin control reciente, independientemente del motivo de consulta.</li><li>Diagnóstico de sospecha y derivación al médico para confirmación diagnóstica.</li><li>Diseño y ejecución del plan de cuidados del paciente hipertenso (NANDA, NIC, NOC).</li><li>Educación terapéutica: modificaciones del estilo de vida, adherencia al tratamiento, autocuidado.</li><li>Seguimiento longitudinal: control periódico de TA, peso, registro en Atenea, evaluación de lesión de órgano diana.</li><li>Detección de mal control y señales de alarma: derivación al médico cuando proceda.</li><li>Coordinación con el médico de familia y, si es necesario, con cardiología o nefrología.</li></ul>
` },
  { id:"hta-2", titulo:"HTA · Medición y valoración enfermera", min:4, html:`
<h3>Técnica correcta de medición de la tensión arterial</h3>
<p>La medición de la TA es el procedimiento más realizado en AP y uno de los más frecuentemente mal ejecutados. Los errores en la técnica son la principal causa de sobrediagnóstico y mal control aparente de la HTA.</p>
<h4>Condiciones previas</h4>
<ul><li>El paciente debe estar sentado con la espalda apoyada, los pies apoyados en el suelo (no cruzados) y el brazo relajado a la altura del corazón.</li><li>Reposo de al menos 5 minutos antes de la medición.</li><li>No haber fumado, tomado café ni hecho ejercicio en los 30 minutos previos.</li><li>Vejiga vacía.</li><li>No hablar durante la medición.</li><li>Temperatura ambiente confortable.</li></ul>
<h4>Técnica paso a paso</h4>
<div class="tbl-scroll"><table><tr><th>Paso</th><th>Descripción</th></tr><tr><td><strong>1. Selección del manguito</strong></td><td>El manguito debe cubrir el 80% de la circunferencia del brazo. Un manguito pequeño sobreestima la TA; uno grande la subestima. Tener disponibles tallas estándar, grande y extra-grande.</td></tr><tr><td><strong>2. Colocación del manguito</strong></td><td>Borde inferior del manguito a 2-3 cm del pliegue del codo. La cámara de aire centrada sobre la arteria braquial. No colocar sobre ropa.</td></tr><tr><td><strong>3. Primera medición</strong></td><td>Ambos brazos en la primera visita. El brazo con valor más alto es el brazo de referencia para mediciones posteriores. Una diferencia > 10 mmHg entre brazos puede indicar patología vascular.</td></tr><tr><td><strong>4. Número de mediciones</strong></td><td>Mínimo 2 mediciones separadas 1-2 minutos. Si difieren > 5 mmHg, realizar una tercera. Registrar la media de las dos últimas.</td></tr><tr><td><strong>5. Posición del esfigmomanómetro</strong></td><td>El manómetro debe estar a la altura de los ojos del explorador. El brazo del paciente a la altura del corazón.</td></tr><tr><td><strong>6. Velocidad de desinflado</strong></td><td>2-3 mmHg por segundo. Un desinflado rápido infravalora la PAD.</td></tr><tr><td><strong>7. Registro</strong></td><td>Anotar PAS (primer ruido de Korotkoff) y PAD (quinto ruido, desaparición). Registrar brazo medido, posición y hora.</td></tr></table></div>
<h4>Errores más frecuentes y su consecuencia</h4>
<div class="tbl-scroll"><table><tr><th>Error</th><th>Consecuencia</th><th>Corrección</th></tr><tr><td>Manguito demasiado pequeño</td><td>Sobreestimación de la TA (falsa HTA).</td><td>Usar talla correcta. Medir circunferencia del brazo.</td></tr><tr><td>Brazo por encima del corazón</td><td>Subestimación de la TA.</td><td>Apoyar el brazo a la altura del corazón.</td></tr><tr><td>Brazo por debajo del corazón</td><td>Sobreestimación de la TA.</td><td>Apoyar el brazo a la altura del corazón.</td></tr><tr><td>Desinflado rápido</td><td>Subestimación de la PAD.</td><td>Desinflar 2-3 mmHg/segundo.</td></tr><tr><td>Piernas cruzadas</td><td>Aumento de PAS hasta 8 mmHg.</td><td>Pies apoyados en el suelo.</td></tr><tr><td>Espalda sin apoyo</td><td>Aumento de PAD hasta 6 mmHg.</td><td>Silla con respaldo. Espalda apoyada.</td></tr><tr><td>Solo una medición</td><td>Alta variabilidad. Diagnóstico impreciso.</td><td>Siempre mínimo 2 mediciones.</td></tr><tr><td>No respetar el reposo previo</td><td>Valores falsamente elevados.</td><td>5 minutos de reposo mínimo.</td></tr></table></div>
<h4>MAPA y AMPA</h4>
<p><strong>MAPA (Monitorización Ambulatoria de Presión Arterial):</strong> registro automático durante 24 horas. Permite detectar HTA de bata blanca, HTA enmascarada y el patrón circadiano. Solicitado por el médico, pero enfermería coloca y retira el dispositivo y descarga los datos.</p>
<p><strong>AMPA (Automedición de la Presión Arterial):</strong> mediciones realizadas por el propio paciente en su domicilio. Enfermería entrena al paciente en la técnica correcta (mismo protocolo que en consulta) y le proporciona una hoja de registro.</p>
<h3>Valoración enfermera: anamnesis y exploración</h3>
<h4>Anamnesis dirigida</h4>
<ul><li>Tiempo de evolución de la HTA y antecedentes de cifras elevadas.</li><li>Tratamiento farmacológico actual: nombre, dosis, horario. Adherencia.</li><li>Antecedentes familiares de enfermedad cardiovascular precoz (< 55 años en varones, < 65 en mujeres).</li><li>Factores de riesgo asociados: tabaco (paquetes-año), diabetes, dislipemia, sedentarismo, obesidad.</li><li>Ingesta de sal, alcohol, cafeína.</li><li>Fármacos que pueden elevar la TA: AINEs, anticonceptivos orales, corticoides, descongestionantes.</li><li>Síntomas de lesión de órgano diana: cefalea, alteraciones visuales, disnea, dolor torácico, edemas, hematuria.</li><li>Historia de crisis hipertensivas o urgencias previas.</li></ul>
<h4>Exploración física básica de enfermería</h4>
<ul><li>Peso, talla e IMC (kg/m²). Objetivo IMC < 25.</li><li>Perímetro abdominal: riesgo cardiovascular si > 102 cm en hombres, > 88 cm en mujeres.</li><li>Frecuencia cardíaca y ritmo.</li><li>Auscultación cardíaca y pulmonar básica (si formación específica).</li><li>Inspección de edemas en extremidades inferiores.</li><li>Fondo de ojo: competencia médica, pero enfermería puede registrar el resultado.</li></ul>
<h4>Datos analíticos a registrar (solicitados por el médico)</h4>
<div class="tbl-scroll"><table><tr><th>Parámetro</th><th>Relevancia clínica</th></tr><tr><td><strong>Glucemia basal</strong></td><td>Detección de diabetes asociada. Objetivo < 100 mg/dL en ayunas.</td></tr><tr><td><strong>Perfil lipídico</strong></td><td>Colesterol total, LDL, HDL, triglicéridos. Necesario para calcular el riesgo cardiovascular.</td></tr><tr><td><strong>Creatinina y FGe</strong></td><td>Función renal. La HTA es causa y consecuencia de enfermedad renal crónica.</td></tr><tr><td><strong>Iones (Na, K)</strong></td><td>El potasio puede alterarse con diuréticos e IECAs. El sodio orienta sobre ingesta de sal.</td></tr><tr><td><strong>Microalbuminuria</strong></td><td>Marcador precoz de lesión renal por HTA. Objetivo: ausencia.</td></tr><tr><td><strong>ECG basal</strong></td><td>Hipertrofia ventricular izquierda, arritmias. Competencia médica, pero enfermería puede realizar el trazado.</td></tr></table></div>
` },
  { id:"hta-3", titulo:"HTA · Objetivos y tratamiento", min:4, html:`
<h3>Objetivos terapéuticos y riesgo cardiovascular</h3>
<h4>Objetivos de control de TA (ESC/ESH 2018)</h4>
<div class="tbl-scroll"><table><tr><th>Población</th><th>Objetivo de TA</th></tr><tr><td><strong>Población general adulta (< 65 años)</strong></td><td>PAS 120-129 mmHg / PAD 70-79 mmHg (objetivo óptimo). Mínimo < 140/90.</td></tr><tr><td><strong>Mayores de 65 años</strong></td><td>PAS 130-139 mmHg. Individualizar según fragilidad y tolerancia.</td></tr><tr><td><strong>Pacientes con DM</strong></td><td>PAS 130-139 mmHg / PAD 70-79 mmHg.</td></tr><tr><td><strong>Pacientes con ERC</strong></td><td>PAS 130-139 mmHg. Especial atención a la función renal con ciertos fármacos.</td></tr><tr><td><strong>Pacientes con enfermedad cardiovascular establecida</strong></td><td>PAS 120-129 mmHg si tolerado.</td></tr></table></div>
<h4>Cálculo del riesgo cardiovascular: SCORE2</h4>
<p>El sistema SCORE2 (Systematic COronary Risk Evaluation 2) estima el riesgo de evento cardiovascular fatal o no fatal a 10 años. Enfermería debe conocerlo para contextualizar el control de la TA y reforzar los mensajes educativos.</p>
<ul><li>Variables incluidas: sexo, edad, tabaco, colesterol no-HDL y PAS sistólica.</li><li>Riesgo bajo: < 5%. Moderado: 5-9%. Alto: 10-14%. Muy alto: ≥ 15% (en < 70 años).</li><li>En mayores de 70 años se usa SCORE2-OP con umbrales diferentes.</li><li>Disponible en la aplicación Atenea y en la web de la SEC (Sociedad Española de Cardiología).</li></ul>
<div class="callout verifica"><span class="lbl">Actualización · Contrato Programa 2026</span><p>En 2026 el Contrato Programa de Centro actualiza las cifras de buen control de la HTA para su indicador, adecuándolas a las guías internacionales: <strong>PAS &lt;130 y PAD &lt;80 mmHg en menores de 80 años; PAS &lt;140 y PAD &lt;80 mmHg a partir de 80 años</strong>. En personas con cardiopatía isquémica o ictus, &lt;130/80. Ten en cuenta que las tablas de este tema reflejan las guías de referencia anteriores; el objetivo individual de cada paciente lo fija el médico y puede ser distinto del umbral del indicador.</p></div>
<h3>Tratamiento no farmacológico: educación terapéutica</h3>
<p>Las modificaciones del estilo de vida son la primera línea de tratamiento en HTA grado 1 de bajo riesgo y son complemento imprescindible del tratamiento farmacológico en todos los demás casos. Enfermería es el profesional de referencia para esta intervención.</p>
<div class="tbl-scroll"><table><tr><th>Medida</th><th>Descripción y efecto esperado</th></tr><tr><td><strong>Reducción de sal</strong></td><td>Objetivo: < 5 g de sal al día (< 2 g de sodio). Evitar sal añadida en la mesa, reducir alimentos procesados, embutidos, conservas y snacks. Cada gramo de reducción de sal baja la PAS 2-4 mmHg.</td></tr><tr><td><strong>Dieta mediterránea</strong></td><td>Rica en frutas, verduras, legumbres, cereales integrales, pescado y aceite de oliva. Reducir carnes rojas y procesadas. Patrón DASH como referencia.</td></tr><tr><td><strong>Reducción de peso</strong></td><td>Cada kg de pérdida de peso reduce la PAS 1 mmHg. Objetivo IMC < 25 y perímetro abdominal normal.</td></tr><tr><td><strong>Ejercicio físico</strong></td><td>Aeróbico de intensidad moderada: 150 minutos/semana (ej. caminar a paso ligero 30 min/día, 5 días/semana). Reduce PAS 4-5 mmHg.</td></tr><tr><td><strong>Reducción del alcohol</strong></td><td>Máximo 14 unidades/semana en hombres, 8 en mujeres. El alcohol eleva directamente la TA.</td></tr><tr><td><strong>Abandono del tabaco</strong></td><td>El tabaco no eleva la TA de forma mantenida, pero multiplica el riesgo cardiovascular. Es prioritario en todo paciente hipertenso fumador.</td></tr><tr><td><strong>Reducción del estrés</strong></td><td>Técnicas de relajación, mindfulness, higiene del sueño. El estrés crónico activa el eje simpático-adrenal y eleva la TA.</td></tr><tr><td><strong>Cafeína</strong></td><td>Puede elevar la TA de forma aguda. No hay evidencia de efecto mantenido, pero se recomienda moderación (máx. 3 tazas/día).</td></tr></table></div>
<div class="callout truco"><span class="lbl">Consejo breve de enfermería: la regla del salero</span><p>Una forma sencilla de explicar la reducción de sal: "Retire el salero de la mesa. Si no lo ve, no lo usa. Lo que ya tiene el alimento cocinado no lo puede controlar fácilmente, pero lo que añade en la mesa sí."</p><p>Enseñar a leer etiquetas: buscar 'sodio' en la información nutricional. < 0,3 g de sodio por 100 g = bajo en sal. > 1,5 g de sodio por 100 g = alto en sal.</p></div>
<h3>Tratamiento farmacológico: lo que debe saber enfermería</h3>
<p>Enfermería no prescribe, pero debe conocer los grupos de fármacos antihipertensivos para reforzar la adherencia, detectar efectos adversos y educar al paciente.</p>
<div class="tbl-scroll"><table><tr><th>Grupo</th><th>Ejemplos</th><th>Efectos adversos / notas de enfermería</th></tr><tr><td>IECAs</td><td>Ramipril, enalapril, lisinopril</td><td>Tos seca (causa más frecuente de abandono). Hiperpotasemia. Contraindicados en embarazo. Protectores renales y cardíacos.</td></tr><tr><td>ARA II</td><td>Losartán, valsartán, olmesartán</td><td>Mejor tolerados que IECAs (no producen tos). Mismas indicaciones. También contraindicados en embarazo.</td></tr><tr><td>Calcioantagonistas</td><td>Amlodipino, lercanidipino</td><td>Edemas maleolares (frecuente, no es signo de insuficiencia cardíaca). Rubefacción facial.</td></tr><tr><td>Diuréticos tiazídicos</td><td>Hidroclorotiazida, clortalidona, indapamida</td><td>Hipopotasemia (vigilar calambres, debilidad). Hiperuricemia. Hiperglucemia.</td></tr><tr><td>Betabloqueantes</td><td>Bisoprolol, atenolol, nebivolol</td><td>Bradicardia. No retirar bruscamente. Indicados si cardiopatía isquémica o insuficiencia cardíaca asociada.</td></tr></table></div>
<div class="callout truco"><span class="lbl">Adherencia terapéutica: el mayor problema en HTA</span><p>La mitad de los pacientes hipertensos abandona el tratamiento en el primer año. Las causas más frecuentes son: efectos adversos, olvidos, sensación de estar bien sin medicación y coste del tratamiento.</p><p>Estrategias enfermeras: simplificación de la pauta (dosis única diaria si es posible), pastillero semanal, recordatorio en el móvil, entrevista motivacional breve en cada visita.</p><p>Pregunta clave no culpabilizadora: '¿Hay días que se le olvida tomar la pastilla? ¿Cuántos días a la semana calcula que la toma?' (Morisky-Green simplificado).</p></div>
` },
  { id:"hta-4", titulo:"HTA · Seguimiento y señales de alarma", min:4, html:`
<h3>Seguimiento: frecuencia y contenido de las visitas</h3>
<div class="tbl-scroll"><table><tr><th>Situación</th><th>Frecuencia y contenido</th></tr><tr><td><strong>HTA de nuevo diagnóstico</strong></td><td>Primera visita de enfermería en los 15 días tras el diagnóstico. Incluir educación terapéutica completa, registro de datos basales y plan de cuidados.</td></tr><tr><td><strong>HTA no controlada (> 140/90)</strong></td><td>Visita mensual hasta lograr control. Revisar adherencia, técnica de medición y factores modificables.</td></tr><tr><td><strong>HTA controlada (< 140/90)</strong></td><td>Visita cada 3-6 meses. Registro de TA, peso, FC, tabaco. Refuerzo educativo. Analítica anual.</td></tr><tr><td><strong>HTA controlada y estable</strong></td><td>Visita anual mínima. Puede espaciarse a 12 meses si muy buen control y baja complejidad.</td></tr><tr><td><strong>HTA + comorbilidad (DM, ERC...)</strong></td><td>Seguimiento más estrecho, integrado con el control de la patología asociada. Individualizar.</td></tr></table></div>
<h4>Contenido mínimo de cada visita de seguimiento</h4>
<ul><li>Medición de TA con técnica correcta (mínimo 2 mediciones).</li><li>Peso e IMC.</li><li>Frecuencia cardíaca.</li><li>Registro de tabaco (consumo activo / ex-fumador / nunca fumador).</li><li>Revisión de la adherencia al tratamiento farmacológico.</li><li>Refuerzo de las medidas de estilo de vida (al menos una por visita).</li><li>Registro en Atenea de todos los parámetros.</li><li>Revisión de resultados analíticos si disponibles.</li></ul>
<h3>Señales de alarma y derivación</h3>
<div class="callout truco"><p><strong>Urgencia hipertensiva — derivación médica en el mismo momento</strong></p><p>→ PAS ≥ 180 mmHg y/o PAD ≥ 110 mmHg SIN síntomas de lesión de órgano diana.</p><p>→ Actuación: repetir la medición tras 5-10 minutos de reposo. Si se confirma, avisar al médico de referencia. No dejar al paciente solo.</p><p>→ El paciente puede recibir tratamiento oral en consulta y ser observado durante 1-2 horas.</p></div>
<div class="callout truco"><p><strong>Emergencia hipertensiva — derivación a urgencias hospitalarias INMEDIATA</strong></p><p>→ PAS ≥ 180 y/o PAD ≥ 120 mmHg CON síntomas de lesión de órgano diana:</p><p>• Neurológicos: cefalea intensa de inicio súbito, déficit neurológico focal, alteración del nivel de consciencia.</p><p>• Cardíacos: dolor torácico, disnea grave, signos de edema agudo de pulmón.</p><p>• Renales: oliguria, hematuria macroscópica.</p><p>• Visuales: pérdida brusca de visión, visión borrosa intensa.</p><p>→ Llamar al 112. Mantener al paciente en reposo. No administrar medicación sin indicación médica.</p></div>
<p><em>Apuntes para estudiantes de enfermería · Centro de Salud Palma Norte · SERMAS</em></p>
<p><em>Tutora de prácticas: Ana Domínguez Rodríguez · Hipertensión arterial · Cartera de Servicios SERMAS</em></p>
` },
  { id:"dm2-1", titulo:"DM2 · Qué es y qué pide la Cartera de Servicios", min:4, html:`
<h3>Definición, diagnóstico y tipos</h3>
<p>La diabetes mellitus (DM) es un grupo de enfermedades metabólicas caracterizadas por hiperglucemia crónica, resultado de defectos en la secreción de insulina, en su acción, o en ambas. La hiperglucemia crónica produce daño progresivo en órganos diana (ojos, riñón, nervios, corazón, vasos).</p>
<h4>Criterios diagnósticos (ADA 2024 / SED)</h4>
<div class="tbl-scroll"><table><tr><th>Criterio</th><th>Valor diagnóstico</th></tr><tr><td><strong>Glucemia basal en ayunas (GBA)</strong></td><td>≥ 126 mg/dL en dos ocasiones distintas (ayuno ≥ 8h).</td></tr><tr><td><strong>Glucemia 2h postsobrecarga (SOG)</strong></td><td>≥ 200 mg/dL tras 75 g de glucosa oral.</td></tr><tr><td><strong>HbA1c</strong></td><td>≥ 6,5% (48 mmol/mol) en laboratorio certificado.</td></tr><tr><td><strong>Glucemia al azar + síntomas</strong></td><td>≥ 200 mg/dL con poliuria, polidipsia o pérdida de peso.</td></tr></table></div>
<p><strong>Prediabetes:</strong> GBA 100-125 mg/dL (glucemia basal alterada) o HbA1c 5,7-6,4%. Intervención activa para prevenir la progresión a DM2.</p>
<h4>Diferencias clave DM1 vs DM2</h4>
<div class="tbl-scroll"><table><tr><th>Característica</th><th>DM tipo 1</th><th>DM tipo 2</th></tr><tr><td>Mecanismo</td><td>Destrucción autoinmune de células beta. Déficit absoluto de insulina.</td><td>Resistencia a la insulina + déficit relativo progresivo.</td></tr><tr><td>Inicio</td><td>Brusco, generalmente en infancia/juventud.</td><td>Insidioso, generalmente > 40 años (pero aumenta en jóvenes).</td></tr><tr><td>Peso habitual</td><td>Normal o bajo.</td><td>Frecuentemente sobrepeso u obesidad.</td></tr><tr><td>Tratamiento</td><td>Insulina siempre.</td><td>Dieta + ejercicio → antidiabéticos orales → insulina si precisa.</td></tr><tr><td>Cetoacidosis</td><td>Frecuente sin tratamiento.</td><td>Rara (salvo situaciones de estrés grave).</td></tr></table></div>
<h3>La DM2 en la cartera de servicios SERMAS</h3>
<p>El Servicio 315 — Atención a la persona diabética de la Cartera de Servicios de AP de la CAM define las actividades mínimas garantizadas para el paciente con DM2.</p>
<div class="tbl-scroll"><table><tr><th>Actividad</th><th>Descripción</th></tr><tr><td><strong>Control glucémico</strong></td><td>HbA1c cada 3-6 meses según control. Glucemia basal en cada visita. Registro en Atenea.</td></tr><tr><td><strong>Control metabólico</strong></td><td>Perfil lipídico, función renal, microalbuminuria, ácido úrico anualmente.</td></tr><tr><td><strong>Exploración del pie</strong></td><td>Revisión anual mínima del pie diabético (o más frecuente según riesgo): pulsos, monofilamento, inspección cutánea. Clasificación de riesgo IWGDF.</td></tr><tr><td><strong>Revisión oftalmológica</strong></td><td>Fondo de ojo o retinografía cada 1-2 años para cribado de retinopatía diabética.</td></tr><tr><td><strong>Control de peso y TA</strong></td><td>En cada visita. La HTA es muy prevalente en el paciente diabético.</td></tr><tr><td><strong>Educación terapéutica</strong></td><td>Automonitorización glucémica, técnica de insulina, dieta, ejercicio, cuidado del pie, hipoglucemia.</td></tr><tr><td><strong>Vacunación</strong></td><td>Gripe anual. Antineumocócica. Hepatitis B si no inmune.</td></tr></table></div>
<h3>Papel de enfermería en el manejo de la DM2</h3>
<ul><li>Valoración integral del paciente diabético en la visita programada.</li><li>Educación terapéutica estructurada: la intervención con mayor evidencia en DM2.</li><li>Entrenamiento en técnica de automonitorización glucémica e insulinoterapia.</li><li>Exploración del pie diabético sistemática (ver guía específica).</li><li>Control y registro de parámetros clínicos: peso, TA, FC, glucemia, HbA1c.</li><li>Detección de hipoglucemias y educación sobre su manejo.</li><li>Detección de complicaciones crónicas y derivación al médico.</li><li>Coordinación con endocrinología, oftalmología, nefrología y podología según necesidad.</li></ul>
` },
  { id:"dm2-2", titulo:"DM2 · Valoración, objetivos y automonitorización", min:4, html:`
<h3>Valoración enfermera</h3>
<h4>Anamnesis dirigida</h4>
<ul><li>Tiempo de evolución de la DM y tratamiento actual (fármacos, dosis, horario).</li><li>Adherencia al tratamiento farmacológico y a las medidas de estilo de vida.</li><li>Automonitorización: frecuencia, registro de resultados, valores habituales.</li><li>Síntomas de hipoglucemia: frecuencia, horario, capacidad de reconocimiento y actuación.</li><li>Síntomas de hiperglucemia: poliuria, polidipsia, visión borrosa, astenia.</li><li>Complicaciones conocidas: retinopatía, nefropatía, neuropatía, cardiopatía, pie diabético.</li><li>Hábitos: dieta, ejercicio, alcohol, tabaco.</li><li>Situaciones especiales: enfermedad intercurrente, cirugía, embarazo (DM gestacional).</li></ul>
<h4>Exploración física</h4>
<ul><li>Peso, talla, IMC y perímetro abdominal (en cada visita).</li><li>Tensión arterial (bilateral en primera visita; brazo de referencia en sucesivas).</li><li>Frecuencia cardíaca.</li><li>Glucemia capilar (en ayunas o 2h postprandial según indicación).</li><li>Exploración del pie diabético completa (mínimo anual): pulsos, monofilamento, inspección. Ver guía específica.</li><li>Inspección de zonas de inyección de insulina si es el caso (lipodistrofias).</li></ul>
<h3>Objetivos de control glucémico y metabólico</h3>
<p>Los objetivos deben individualizarse según la edad, la esperanza de vida, las comorbilidades y las preferencias del paciente. Estos son los objetivos generales de referencia en la CAM:</p>
<div class="tbl-scroll"><table><tr><th>Parámetro</th><th>Objetivo</th></tr><tr><td><strong>HbA1c</strong></td><td>< 7% (< 53 mmol/mol) en la mayoría de adultos. < 7,5-8% en mayores, pacientes frágiles o con hipoglucemias frecuentes.</td></tr><tr><td><strong>Glucemia basal (ayunas)</strong></td><td>80-130 mg/dL.</td></tr><tr><td><strong>Glucemia postprandial (2h)</strong></td><td>< 180 mg/dL.</td></tr><tr><td><strong>Colesterol LDL</strong></td><td>< 100 mg/dL. < 70 mg/dL si enfermedad cardiovascular establecida.</td></tr><tr><td><strong>Colesterol HDL</strong></td><td>> 40 mg/dL en hombres, > 50 mg/dL en mujeres.</td></tr><tr><td><strong>Triglicéridos</strong></td><td>< 150 mg/dL.</td></tr><tr><td><strong>Tensión arterial</strong></td><td>< 130/80 mmHg.</td></tr><tr><td><strong>IMC</strong></td><td>Objetivo pérdida de peso si IMC > 25. Una pérdida del 5-10% mejora significativamente el control glucémico.</td></tr><tr><td><strong>Tabaco</strong></td><td>Abstinencia total.</td></tr></table></div>
<h3>Automonitorización glucémica: técnica e interpretación</h3>
<h4>Técnica de glucemia capilar</h4>
<ul><li>Lavarse las manos con agua y jabón y secarlas bien. No usar alcohol (puede falsear el resultado).</li><li>Pinchar en el lateral de la yema del dedo (menos doloroso y con más vascularización que el centro).</li><li>La primera gota de sangre se descarta (puede estar diluida con líquido tisular).</li><li>Aplicar la segunda gota a la tira reactiva sin frotar ni exprimir en exceso.</li><li>Rotar los dedos y los puntos de punción para evitar callosidades.</li><li>Registrar el resultado con la hora y si es preprandial o postprandial.</li><li>Calibrar el glucómetro periódicamente y comprobar la fecha de caducidad de las tiras.</li></ul>
<h4>Frecuencia de automonitorización</h4>
<div class="tbl-scroll"><table><tr><th>Situación</th><th>Frecuencia recomendada</th></tr><tr><td><strong>DM2 con dieta y ejercicio / antidiabéticos orales sin riesgo de hipoglucemia</strong></td><td>No imprescindible rutinariamente. Útil en situaciones de enfermedad intercurrente o dudas.</td></tr><tr><td><strong>DM2 con secretagogos (sulfonilureas) o insulina</strong></td><td>Mínimo 1-2 veces al día. Más frecuente en mal control o ajuste de dosis.</td></tr><tr><td><strong>DM2 con insulina basal</strong></td><td>Glucemia basal (ayunas) diaria como mínimo.</td></tr><tr><td><strong>DM2 con múltiples dosis de insulina (MDI)</strong></td><td>Preprandial en cada comida + antes de dormir. Postprandial si mal control.</td></tr></table></div>
<h4>Sistemas de monitorización continua de glucosa (MCG)</h4>
<p>Los sistemas MCG (Freestyle Libre®, Dexcom®) miden la glucosa en el líquido intersticial de forma continua o bajo demanda. La CAM financia el sistema flash (Freestyle Libre) para pacientes con DM1 y para DM2 con múltiples dosis de insulina según criterios específicos.</p>
<ul><li>Enfermería debe saber colocar el sensor, entrenar al paciente en su uso e interpretar los informes básicos (tiempo en rango, curvas de glucosa).</li><li>Tiempo en rango (TIR) objetivo: > 70% del tiempo entre 70-180 mg/dL.</li></ul>
` },
  { id:"dm2-3", titulo:"DM2 · Tratamiento e insulinoterapia", min:5, html:`
<h3>Tratamiento no farmacológico: dieta y ejercicio</h3>
<h4>Alimentación en la DM2</h4>
<p>No existe una dieta única para el paciente diabético. La evidencia apoya un patrón de alimentación mediterráneo o equivalente, con estas características:</p>
<ul><li>Hidratos de carbono: no eliminar, sino seleccionar. Preferir cereales integrales, legumbres, verduras. Limitar azúcares simples (refrescos, dulces, zumos).</li><li>Grasas: reducir grasas saturadas (carnes rojas, embutidos, bollería). Potenciar grasas insaturadas (aceite de oliva, pescado azul, frutos secos).</li><li>Proteínas: sin restricción en ausencia de nefropatía. Con nefropatía: 0,8 g/kg/día.</li><li>Fibra: al menos 25-30 g/día. Enlentece la absorción de glucosa y mejora el control postprandial.</li><li>Alcohol: máximo 1 unidad/día en mujeres, 2 en hombres. Riesgo de hipoglucemia con insulina o sulfonilureas si se consume sin alimento.</li><li>Distribución horaria: 3-5 comidas al día. Evitar ayunos prolongados y atracones.</li></ul>
<div class="callout truco"><span class="lbl">Mensaje educativo clave: el método del plato</span><p>Dividir el plato en tres partes: 1/2 de verduras (crudas o cocinadas), 1/4 de proteína (pollo, pescado, legumbre), 1/4 de hidratos de carbono (arroz, pasta, pan integral, patata).</p><p>Es un mensaje visual, sencillo y sin necesidad de contar calorías. Muy útil en pacientes con baja alfabetización sanitaria.</p></div>
<h4>Ejercicio físico en la DM2</h4>
<ul><li>Ejercicio aeróbico: al menos 150 minutos/semana de intensidad moderada (caminar a paso ligero, nadar, bicicleta). Reduce la HbA1c entre 0,5-1%.</li><li>Ejercicio de resistencia: 2-3 sesiones/semana (ejercicios con peso, bandas elásticas). Mejora la sensibilidad a la insulina.</li><li>Romper el sedentarismo: levantarse y moverse 5 minutos cada 30 minutos de estar sentado.</li><li>Precauciones: en pacientes con insulina o sulfonilureas, riesgo de hipoglucemia durante y tras el ejercicio. Medir glucemia antes, durante (si sesión larga) y después.</li><li>Contraindicaciones relativas: retinopatía proliferativa activa, neuropatía autonómica grave, glucemia > 300 mg/dL o < 100 mg/dL antes del ejercicio.</li></ul>
<h3>Tratamiento farmacológico: lo que debe saber enfermería</h3>
<div class="tbl-scroll"><table><tr><th>Fármaco / grupo</th><th>Características</th><th>Nota de enfermería</th></tr><tr><td>Metformina</td><td>Primera línea. Reduce glucemia sin hipoglucemia. Contraindicada en FGe < 30. Efectos GI frecuentes (náuseas, diarrea): tomar con comida.</td><td>Recordar tomar con las comidas. No suspender sin consultar al médico aunque haya molestias GI iniciales.</td></tr><tr><td>iSGLT2 (gliflozinas)</td><td>Empagliflozina, dapagliflozina. Elimina glucosa por orina. Protectores renales y cardíacos. Riesgo de infecciones genitales por hongos e ITU.</td><td>Higiene genital cuidadosa. Hidratación adecuada. Suspender si vómitos o cirugía.</td></tr><tr><td>GLP-1 (análogos)</td><td>Semaglutida, liraglutida. Inyectables (algunos orales). Reducen peso. Náuseas frecuentes al inicio. Muy alta evidencia cardiovascular.</td><td>Inyección subcutánea semanal o diaria. Conservar en nevera. Náuseas mejoran con el tiempo.</td></tr><tr><td>Sulfonilureas</td><td>Glibenclamida, glimepirida. Secretagogos. Riesgo de hipoglucemia. Poco usadas de primera línea actualmente.</td><td>Alto riesgo de hipoglucemia. No saltarse comidas. Educación sobre síntomas de hipoglucemia.</td></tr><tr><td>DPP-4 (gliptinas)</td><td>Sitagliptina, alogliptina. Buena tolerancia. Sin hipoglucemia. Eficacia moderada.</td><td>Generalmente bien toleradas. No usar con GLP-1.</td></tr><tr><td>Insulinas</td><td>Ver bloque específico.</td><td>Ver bloque específico.</td></tr></table></div>
<h3>Insulinoterapia: técnica de administración</h3>
<h4>Tipos de insulina</h4>
<div class="tbl-scroll"><table><tr><th>Tipo</th><th>Características y uso</th></tr><tr><td><strong>Insulina basal (lenta)</strong></td><td>Glargina (Lantus®, Toujeo®), detemir (Levemir®), degludec (Tresiba®). Acción prolongada (12-42h). Se administra 1 vez al día (o 2 en casos especiales). Cubre la glucemia en ayunas.</td></tr><tr><td><strong>Insulina rápida / ultrarrápida</strong></td><td>Aspart (Novorapid®), lispro (Humalog®), glulisina (Apidra®). Acción muy rápida (pico 1-2h). Se administra antes de las comidas. Cubre la glucemia postprandial.</td></tr><tr><td><strong>Insulina regular (humana)</strong></td><td>Actrapid®, Humulina Regular®. Más lenta que las ultrarrápidas. Se usa en bomba o en situaciones especiales.</td></tr><tr><td><strong>Mezclas (bifásicas)</strong></td><td>Novomix 30®, Humalog Mix 25®. Combinan insulina basal y rápida en una misma jeringa. 2 inyecciones al día con las comidas principales.</td></tr></table></div>
<h4>Técnica de inyección subcutánea</h4>
<ul><li>Lavado de manos antes de la preparación.</li><li>Revisar el aspecto de la insulina: la basal debe ser transparente (excepto mezclas, que son turbias → agitar suavemente 10 veces antes de usar). Desechar si hay partículas o cambio de color.</li><li>Cargar la dosis en el dispositivo (pluma o jeringa). Purgar la aguja antes de inyectar (una unidad para eliminar el aire).</li><li>Zonas de inyección: abdomen (acción más rápida, preferida para insulina rápida), muslo (más lenta, preferida para basal), glúteo y brazo (parte posterior). Rotar sistemáticamente los puntos de inyección dentro de cada zona.</li><li>Hacer un pellizco suave de la piel si el pliegue es escaso (pacientes delgados). En pacientes con obesidad, no es necesario.</li><li>Ángulo de inyección: 90° en la mayoría de casos. 45° en pacientes muy delgados para evitar inyección intramuscular.</li><li>Introducir la aguja y administrar la insulina de forma lenta. Mantener la aguja en la piel 10 segundos antes de retirarla (evita que salga el líquido).</li><li>No frotar la zona tras la inyección (modifica la absorción).</li><li>Desechar la aguja en contenedor rígido de residuos biosanitarios. Nunca en el cubo de basura doméstico.</li></ul>
<h4>Lipodistrofias: el problema más frecuente y más ignorado</h4>
<p>La lipodistrofia (hipertrofia o lipoatrofia del tejido subcutáneo) aparece cuando el paciente no rota las zonas de inyección. La insulina administrada en un lipodistrofia se absorbe de forma errática e impredecible, lo que explica muchos casos de mal control glucémico aparentemente inexplicable.</p>
<ul><li>En cada visita: inspeccionar y palpar las zonas de inyección. La lipohipertrofia es una zona de tejido más duro, irregular, que el paciente frecuentemente no percibe.</li><li>Instruir al paciente para que rote las zonas y evite inyectar en lipodistrofias.</li><li>Si hay lipodistrofia establecida: cambiar de zona. El control glucémico mejora a menudo de forma significativa.</li></ul>
` },
  { id:"dm2-4", titulo:"DM2 · Hipoglucemia, seguimiento y complicaciones", min:4, html:`
<h3>Hipoglucemia: reconocimiento y actuación</h3>
<p><strong>Definición:</strong> glucemia < 70 mg/dL. Hipoglucemia grave: < 54 mg/dL o cualquier hipoglucemia que requiera ayuda de terceros.</p>
<h4>Síntomas</h4>
<div class="tbl-scroll"><table><tr><th>Tipo</th><th>Síntomas</th></tr><tr><td><strong>Adrenérgicos (glucemia 50-70 mg/dL)</strong></td><td>Temblor, palpitaciones, sudoración, palidez, hambre intensa, ansiedad. Son síntomas de alarma que permiten actuar a tiempo.</td></tr><tr><td><strong>Neuroglucopénicos (glucemia < 50 mg/dL)</strong></td><td>Confusión, dificultad para hablar, visión doble, torpeza motora, comportamiento extraño, pérdida de consciencia.</td></tr><tr><td><strong>Hipoglucemia inadvertida</strong></td><td>El paciente no percibe los síntomas adrenérgicos (frecuente en DM de larga evolución, neuropatía autonómica, betabloqueantes). Mayor riesgo de hipoglucemia grave.</td></tr></table></div>
<h4>Regla del 15 — Actuación en hipoglucemia leve-moderada (paciente consciente)</h4>
<ul><li>15 g de hidratos de carbono de absorción rápida: 150 mL de zumo de naranja o refresco azucarado (no light), 3-4 sobres de azúcar, 3-4 gominolas, 1 vaso de leche entera.</li><li>Esperar 15 minutos y volver a medir la glucemia.</li><li>Si glucemia < 70 mg/dL: repetir los 15 g de HC.</li><li>Si glucemia ≥ 70 mg/dL y la próxima comida está lejos (> 1h): tomar un pequeño snack (una fruta + un lácteo o un trozo de pan).</li><li>Registrar el episodio y la causa probable. Comunicar al médico si es recurrente.</li></ul>
<div class="callout truco"><p><strong>Hipoglucemia grave (paciente inconsciente o incapaz de tragar)</strong></p><p>→ NO administrar nada por boca: riesgo de aspiración.</p><p>→ Glucagón intramuscular o subcutáneo (kit de emergencia): 1 mg en adultos. El familiar o cuidador debe estar entrenado en su uso.</p><p>→ En el centro de salud: glucosa hipertónica intravenosa (30-50 mL de glucosa al 50%) administrada por médico.</p><p>→ Activar el 112 si no se dispone de glucagón ni de acceso venoso.</p></div>
<h3>Seguimiento y complicaciones crónicas</h3>
<h4>Calendario de revisiones en el paciente con DM2 bien controlado</h4>
<div class="tbl-scroll"><table><tr><th>Frecuencia</th><th>Actividad</th></tr><tr><td><strong>En cada visita</strong></td><td>Peso, IMC, TA, FC, glucemia capilar, revisión de adherencia y técnica (si usa insulina).</td></tr><tr><td><strong>Cada 3-6 meses</strong></td><td>HbA1c (cada 3 meses si mal control o ajuste de tratamiento; cada 6 meses si buen control).</td></tr><tr><td><strong>Anual</strong></td><td>Analítica completa (perfil lipídico, función renal, microalbuminuria, hemograma). ECG. Exploración del pie. Derivación a oftalmología para retinografía.</td></tr><tr><td><strong>Según riesgo de pie</strong></td><td>Exploración del pie cada 1-12 meses según categoría de riesgo IWGDF (ver guía específica).</td></tr></table></div>
<h4>Complicaciones crónicas: señales de alerta para enfermería</h4>
<div class="tbl-scroll"><table><tr><th>Complicación</th><th>Señal de alerta y actuación enfermera</th></tr><tr><td><strong>Retinopatía diabética</strong></td><td>Visión borrosa, destellos, moscas volantes, pérdida brusca de visión → derivación urgente a oftalmología.</td></tr><tr><td><strong>Nefropatía diabética</strong></td><td>Microalbuminuria progresiva, elevación de creatinina, edemas, HTA de difícil control → ajuste de tratamiento y seguimiento estrecho.</td></tr><tr><td><strong>Neuropatía periférica</strong></td><td>Parestesias, dolor neuropático (ardor, agujas), pérdida de sensibilidad → exploración del pie, derivación si dolor intenso.</td></tr><tr><td><strong>Cardiopatía isquémica</strong></td><td>Dolor torácico, disnea de esfuerzo, síncope, ECG alterado → derivación urgente.</td></tr><tr><td><strong>Pie diabético</strong></td><td>Cualquier herida, eritema, calor o deformidad nueva → actuación inmediata (ver guía específica).</td></tr><tr><td><strong>Hipoglucemias recurrentes</strong></td><td>Revisar pauta, adherencia, zonas de inyección, ejercicio, dieta. Comunicar al médico para ajuste.</td></tr></table></div>
<p><em>Apuntes para estudiantes de enfermería · Centro de Salud Palma Norte · SERMAS</em></p>
<p><em>Tutora de prácticas: Ana Domínguez Rodríguez · Diabetes mellitus tipo 2 · Cartera de Servicios SERMAS</em></p>
` },
  { id:"epoc-1", titulo:"EPOC · Qué es y qué pide la Cartera de Servicios", min:4, html:`
<h3>Definición, fisiopatología y epidemiología</h3>
<p>La Enfermedad Pulmonar Obstructiva Crónica (EPOC) es una enfermedad prevenible y tratable, caracterizada por síntomas respiratorios persistentes y limitación al flujo aéreo debida a anomalías de las vías aéreas y/o alveolares, generalmente causadas por exposición significativa a partículas o gases nocivos, siendo el tabaco el principal factor etiológico.</p>
<p><strong>Fisiopatología resumida:</strong> el humo del tabaco activa una respuesta inflamatoria crónica que destruye el parénquima pulmonar (enfisema) y produce hipertrofia e hipersecreción glandular en los bronquios (bronquitis crónica). El resultado es una obstrucción irreversible (o parcialmente reversible) al flujo aéreo.</p>
<p><strong>Prevalencia en España:</strong> aproximadamente el 11% de la población entre 40 y 80 años. El 75% de los casos están infradiagnosticados. La EPOC es la cuarta causa de muerte en España.</p>
<h3>La EPOC en la cartera de servicios SERMAS</h3>
<p>El Servicio 320 — Atención a la persona con EPOC de la Cartera de Servicios de la CAM establece las actividades mínimas garantizadas en AP:</p>
<div class="tbl-scroll"><table><tr><th>Actividad</th><th>Descripción</th></tr><tr><td><strong>Cribado y diagnóstico</strong></td><td>Espirometría forzada en todo fumador ≥ 35 años con síntomas respiratorios. Diagnóstico confirmado por espirometría post-broncodilatador.</td></tr><tr><td><strong>Consejo antitabaco</strong></td><td>En cada visita. Ofrecer derivación a programa de deshabituación tabáquica. Intervención breve sistematizada (protocolo 5As).</td></tr><tr><td><strong>Valoración del impacto</strong></td><td>Cuestionario CAT o escala mMRC en cada visita para valorar síntomas y calidad de vida.</td></tr><tr><td><strong>Control del tratamiento</strong></td><td>Revisión del tratamiento inhalado, técnica de inhalación y adherencia en cada visita.</td></tr><tr><td><strong>Rehabilitación respiratoria</strong></td><td>Derivación a programa de rehabilitación en EPOC moderada-grave.</td></tr><tr><td><strong>Vacunación</strong></td><td>Antigripal anual. Antineumocócica. COVID-19 según calendario vigente.</td></tr><tr><td><strong>Plan de acción ante exacerbación</strong></td><td>Documento personalizado que el paciente conoce y usa ante el primer síntoma de exacerbación.</td></tr></table></div>
` },
  { id:"epoc-2", titulo:"EPOC · Espirometría y clasificación GOLD", min:4, html:`
<h3>Espirometría forzada: técnica e interpretación</h3>
<p>La espirometría es la prueba diagnóstica de referencia en la EPOC. En AP, enfermería realiza la espirometría y el médico interpreta los resultados. Una buena técnica es imprescindible para obtener resultados fiables.</p>
<h4>Material necesario</h4>
<ul><li>Espirómetro calibrado (calibración diaria con jeringa de 3 litros).</li><li>Boquillas desechables de un solo uso.</li><li>Pinzas nasales.</li><li>Broncodilatador de acción corta (salbutamol 400 mcg = 4 pulsaciones) para la espirometría post-broncodilatador.</li></ul>
<h4>Preparación del paciente</h4>
<ul><li>No fumar en las 4 horas previas.</li><li>No hacer ejercicio intenso en la hora previa.</li><li>No haber tomado broncodilatadores de acción corta en las 4 horas previas (o de acción larga en las 12-24h previas) si se va a realizar espirometría post-BD.</li><li>Ropa no restrictiva. Retirar prótesis dental si es inestable.</li><li>El paciente debe conocer la maniobra antes de realizarla: explicar y demostrar.</li></ul>
<h4>Técnica de la maniobra de capacidad vital forzada (CVF)</h4>
<ul><li>Paso 1 — Posición: paciente sentado erguido, pies apoyados en el suelo, barbilla ligeramente elevada.</li><li>Paso 2 — Introducir la boquilla en la boca con un buen sellado de los labios. Colocar las pinzas nasales.</li><li>Paso 3 — Inspiración máxima y rápida (hasta el límite de la capacidad pulmonar total).</li><li>Paso 4 — Inicio del soplo de forma brusca, explosiva y sin dudar. El primer segundo es el más crítico.</li><li>Paso 5 — Mantener el soplo de forma continua y fuerte durante al menos 6 segundos (en adultos) o hasta que el flujo se detenga. Animar al paciente verbalmente: '¡sigue, sigue, sigue!'</li><li>Paso 6 — Fin de la maniobra: criterio de tiempo (≥ 6 segundos) o de plateau (flujo < 25 mL en el último segundo).</li><li>Repetir hasta obtener 3 maniobras aceptables y 2 reproducibles (diferencia < 150 mL entre las dos mejores).</li></ul>
<div class="callout truco"><span class="lbl">Criterios de aceptabilidad de la maniobra</span><p>→ Inicio brusco (pico de flujo precoz y bien definido). Sin vacilaciones.</p><p>→ Sin artefactos: tos en el primer segundo, cierre glótico, escape de aire por los lados.</p><p>→ Duración ≥ 6 segundos con plateau.</p><p>→ Finalización completa sin interrupción del paciente.</p><p>Si la maniobra no cumple estos criterios, NO es válida aunque el espirómetro la registre.</p></div>
<h4>Interpretación básica de la espirometría</h4>
<div class="tbl-scroll"><table><tr><th>Parámetro</th><th>Descripción</th></tr><tr><td><strong>FVC (Capacidad Vital Forzada)</strong></td><td>Volumen total de aire exhalado en la maniobra forzada. Normal: > 80% del valor de referencia.</td></tr><tr><td><strong>FEV1 (Volumen espiratorio máximo en 1 segundo)</strong></td><td>Volumen exhalado en el primer segundo. Indicador de obstrucción. Normal: > 80% del teórico.</td></tr><tr><td><strong>Cociente FEV1/FVC</strong></td><td>Patrón obstructivo si < 70% (criterio GOLD post-broncodilatador). Este cociente fijo es el criterio diagnóstico de EPOC.</td></tr><tr><td><strong>Patrón obstructivo</strong></td><td>FEV1/FVC < 70% con FVC normal o reducida. Típico de EPOC y asma.</td></tr><tr><td><strong>Patrón restrictivo</strong></td><td>FVC < 80% con FEV1/FVC normal o elevado. Enfermedades intersticiales, obesidad, deformidades torácicas.</td></tr><tr><td><strong>Patrón mixto</strong></td><td>FEV1/FVC < 70% + FVC < 80%. Combinación de obstrucción y restricción.</td></tr></table></div>
<p><strong>Prueba broncodilatadora:</strong> se administran 400 mcg de salbutamol (4 pulsaciones con cámara espaciadora) y se repite la espirometría a los 15-20 minutos. Si el FEV1 mejora ≥ 12% y ≥ 200 mL → respuesta positiva (más compatible con asma). En EPOC la obstrucción es poco o nada reversible.</p>
<h3>Clasificación de la gravedad: GOLD 2024</h3>
<h4>Limitación al flujo aéreo (post-broncodilatador)</h4>
<div class="tbl-scroll"><table><tr><th>Categoría</th><th>FEV1 y características</th></tr><tr><td><strong>GOLD 1 — Leve</strong></td><td>FEV1 ≥ 80% del valor teórico. Pocos síntomas. Frecuentemente infradiagnosticado.</td></tr><tr><td><strong>GOLD 2 — Moderado</strong></td><td>FEV1 50-79%. Disnea de esfuerzo moderado. Mayor riesgo de exacerbaciones.</td></tr><tr><td><strong>GOLD 3 — Grave</strong></td><td>FEV1 30-49%. Disnea de pequeños esfuerzos. Exacerbaciones frecuentes.</td></tr><tr><td><strong>GOLD 4 — Muy grave</strong></td><td>FEV1 < 30%. Disnea de reposo. Insuficiencia respiratoria. Alto riesgo de muerte.</td></tr></table></div>
<h4>Evaluación de síntomas e impacto: escalas de uso en AP</h4>
<p><strong>Escala mMRC (Modified Medical Research Council):</strong> gradúa la disnea del 0 al 4. grado 0: disnea solo con ejercicio intenso. Grado 4: disnea en reposo que impide salir de casa. mMRC ≥ 2 indica más síntomas.</p>
<p><strong>Cuestionario CAT (COPD Assessment Test):</strong> 8 preguntas que valoran el impacto de la EPOC en la vida diaria. Puntuación 0-40. CAT < 10: poco impacto. CAT ≥ 10: alto impacto. Herramienta validada y fácil de administrar en consulta.</p>
` },
  { id:"epoc-3", titulo:"EPOC · Valoración enfermera y tratamiento no farmacológico", min:4, html:`
<h3>Papel de enfermería en el manejo de la EPOC</h3>
<ul><li>Realización de espirometrías de diagnóstico y seguimiento.</li><li>Valoración del paciente en cada visita: síntomas, tolerancia al ejercicio, exacerbaciones recientes.</li><li>Educación sobre la enfermedad, el tratamiento y los factores de riesgo.</li><li>Entrenamiento y revisión de la técnica de inhalación en cada visita.</li><li>Consejo antitabaco estructurado (protocolo de las 5As) en cada contacto.</li><li>Detección precoz de exacerbaciones y actuación según plan de acción personalizado.</li><li>Control de la saturación de oxígeno y derivación si procede.</li><li>Educación sobre la oxigenoterapia domiciliaria si el paciente la tiene prescrita.</li><li>Coordinación con neumología, rehabilitación respiratoria y trabajo social.</li></ul>
<h3>Valoración enfermera: anamnesis y exploración</h3>
<h4>Anamnesis dirigida</h4>
<ul><li>Historia tabáquica: paquetes-año (n.º cigarrillos/día ÷ 20 × años de fumador). Situación actual (fumador activo, ex, nunca).</li><li>Síntomas principales: disnea (escala mMRC), tos, expectoración (cantidad, aspecto, cambios recientes).</li><li>Exacerbaciones en el último año: número, necesidad de antibiótico o corticoide oral, ingresos hospitalarios.</li><li>Tratamiento actual: nombre del inhalador, dosis, frecuencia. Técnica autorreferida.</li><li>Adherencia: ¿lo usa siempre? ¿se olvida? ¿lo usa solo cuando nota que lo necesita?</li><li>Oxigenoterapia domiciliaria: horas de uso al día, concentración, equipo disponible en casa.</li><li>Impacto en la vida diaria: qué actividades ha dejado de hacer, calidad del sueño, estado de ánimo.</li><li>Vacunación: gripe, neumococo, COVID-19.</li></ul>
<h4>Exploración física</h4>
<ul><li>Frecuencia respiratoria (normal: 12-20 rpm). La taquipnea en reposo es signo de gravedad.</li><li>Saturación de oxígeno con pulsioxímetro (en reposo). Normal ≥ 95%. < 90% en reposo → derivación urgente.</li><li>Frecuencia cardíaca y tensión arterial.</li><li>Inspección del tórax: tórax en barril (hiperinsuflación), tiraje intercostal, uso de musculatura accesoria.</li><li>Auscultación pulmonar: sibilancias espiratorias (broncoespasmo), crepitantes (infección o insuficiencia cardíaca), murmullo vesicular disminuido (enfisema).</li><li>Inspección de extremidades: dedos en palillo de tambor (enfermedad avanzada), cianosis periférica, edemas (cor pulmonale).</li><li>Peso e IMC: la pérdida de peso y la sarcopenia son marcadores de mal pronóstico en EPOC.</li></ul>
<h3>Tratamiento no farmacológico</h3>
<h4>Abandono del tabaco — prioridad absoluta</h4>
<p>Es la única medida que modifica la historia natural de la EPOC. Incluso en estadios avanzados, dejar de fumar enlentece la progresión de la enfermedad y mejora los síntomas.</p>
<h4>Protocolo de las 5As en AP:</h4>
<ul><li>Averiguar: preguntar en cada visita si fuma.</li><li>Aconsejar: dar un consejo claro, personalizado y firme de abandono.</li><li>Apreciar: valorar la disposición al cambio (estadios de Prochaska).</li><li>Ayudar: ofrecer apoyo conductual y farmacológico (vareniclina, bupropión, TSN).</li><li>Acordar: fijar una fecha de abandono y programar visita de seguimiento.</li></ul>
<h4>Rehabilitación respiratoria</h4>
<p>Programa multidisciplinar de ejercicio físico supervisado, educación y soporte psicosocial. Indicado en EPOC moderada-grave (GOLD 2-4). Reduce las exacerbaciones, mejora la capacidad funcional y la calidad de vida. La derivación es competencia del médico, pero enfermería debe informar al paciente de su existencia y beneficios.</p>
<h4>Ejercicio físico y actividad adaptada</h4>
<ul><li>Incluso en EPOC leve: caminar a paso moderado 30 minutos al día, 5 días/semana.</li><li>Ejercicios de fortalecimiento de extremidades superiores e inferiores.</li><li>Técnicas de ahorro de energía: planificar actividades, descanso pautado, técnicas posturales para reducir la disnea.</li><li>Posición de alivio de la disnea: sentado inclinado hacia adelante, codos apoyados en las rodillas.</li></ul>
<h4>Higiene bronquial</h4>
<ul><li>Drenaje postural y fisioterapia respiratoria: en pacientes con hipersecreción bronquial significativa.</li><li>Hidratación adecuada: facilita la fluidificación de las secreciones.</li><li>Humidificación del ambiente en invierno si el paciente lo percibe beneficioso.</li></ul>
` },
  { id:"epoc-4", titulo:"EPOC · Inhaladores y oxigenoterapia", min:4, html:`
<h3>Tratamiento farmacológico y técnica de inhaladores</h3>
<h4>Grupos farmacológicos principales en EPOC</h4>
<div class="tbl-scroll"><table><tr><th>Grupo</th><th>Ejemplos y características</th></tr><tr><td><strong>LAMA (anticolinérgico de larga duración)</strong></td><td>Tiotropio (Spiriva®), glicopirronio, umeclidinio. Primera línea en EPOC estable. 1 vez al día. Reduce exacerbaciones y mejora la función pulmonar.</td></tr><tr><td><strong>LABA (beta-2 agonista de larga duración)</strong></td><td>Formoterol, indacaterol, salmeterol, olodaterol. En combinación con LAMA o ICS. 1-2 veces al día.</td></tr><tr><td><strong>ICS (corticoide inhalado)</strong></td><td>Fluticasona, budesonida. No en monoterapia en EPOC. En combinación LABA+ICS o triple terapia si exacerbaciones frecuentes y eosinofilia.</td></tr><tr><td><strong>SABA (beta-2 agonista de corta duración)</strong></td><td>Salbutamol (Ventolin®), terbutalina. Broncodilatador de rescate. Inicio rápido (5 min). Duración 4-6h.</td></tr><tr><td><strong>SAMA (anticolinérgico de corta duración)</strong></td><td>Ipratropio. Inicio más lento (15-30 min). Puede combinarse con SABA en exacerbaciones.</td></tr><tr><td><strong>Teofilina</strong></td><td>Uso muy limitado en AP. Margen terapéutico estrecho, muchas interacciones. Reservado para casos seleccionados.</td></tr></table></div>
<h4>Tipos de dispositivos inhaladores y técnica</h4>
<div class="tbl-scroll"><table><tr><th>Tipo</th><th>Ejemplos</th><th>Técnica resumida</th></tr><tr><td>Inhalador presurizado (pMDI)</td><td>Ventolin® inhalador, muchos ICS y combinaciones.</td><td>1. Agitar el inhalador. 2. Espirar lentamente vaciando los pulmones. 3. Colocar la boquilla en la boca sellando bien los labios (o usar cámara espaciadora). 4. Iniciar inspiración lenta y profunda y a la vez presionar el inhalador. 5. Continuar inspirando lentamente hasta llenar los pulmones. 6. Apnea 10 segundos. 7. Espirar lentamente por la nariz.</td></tr><tr><td>Cámara espaciadora</td><td>Uso siempre con pMDI en pacientes que no coordinan.</td><td>Acoplar el inhalador a la cámara. Presionar y hacer 5-6 inspiraciones lentas y profundas. La cámara elimina la necesidad de coordinar la pulsación con la inspiración.</td></tr><tr><td>Inhalador de polvo seco (DPI)</td><td>Turbuhaler® (Spiriva Respimat, Symbicort®), Ellipta®, Breezhaler®.</td><td>1. Cargar la dosis según el dispositivo específico. 2. Espirar FUERA del dispositivo (nunca soplar dentro). 3. Colocar en la boca y sellar. 4. Inspiración rápida y profunda (los dispositivos DPI requieren flujo inspiratorio suficiente). 5. Apnea 10 segundos. 6. Espirar lentamente.</td></tr><tr><td>Nebulizador</td><td>Pacientes que no pueden usar otros dispositivos o en exacerbaciones.</td><td>Cargar la medicación en la cámara del nebulizador. Respiración normal con boca abierta durante 10-15 minutos hasta que deje de nebulizar. Limpiar y secar el equipo tras cada uso.</td></tr></table></div>
<div class="callout truco"><p><strong>Revisión de la técnica inhalatoria: la intervención más rentable en EPOC</strong></p><p>El 70-80% de los pacientes con EPOC cometen errores en la técnica de inhalación. Un mal uso del inhalador equivale a no tomar el tratamiento. Revisar la técnica en CADA visita.</p><p>Método: pedir al paciente que realice la maniobra completa delante de la enfermera. Identificar el error. Corregir. Pedir que repita. Registrar.</p><p>Errores más frecuentes en pMDI: no agitar, no espirar antes, coordinación incorrecta entre pulsación e inspiración. En DPI: espirar dentro del dispositivo, flujo inspiratorio insuficiente.</p></div>
<h3>Oxigenoterapia domiciliaria</h3>
<p>La oxigenoterapia continua domiciliaria (OCD) es el único tratamiento (junto al abandono del tabaco) que ha demostrado aumentar la supervivencia en pacientes con EPOC grave e insuficiencia respiratoria crónica.</p>
<h4>Criterios de indicación (prescripción médica)</h4>
<ul><li>PaO2 ≤ 55 mmHg en reposo en dos determinaciones con 3 semanas de diferencia en situación estable.</li><li>PaO2 56-59 mmHg con signos de cor pulmonale, poliglobulia o alteraciones del ritmo cardíaco.</li><li>SatO2 ≤ 88% en reposo o desaturación ≥ 88% nocturna o con esfuerzo (oxigenoterapia ambulatoria o nocturna).</li></ul>
<h4>Educación al paciente con oxigenoterapia domiciliaria</h4>
<ul><li>Uso mínimo de 16-18 horas al día, incluidas las horas de sueño, para que sea efectivo.</li><li>Flujo prescrito por el médico: no modificarlo por iniciativa propia aunque sienta más disnea.</li><li>Normas de seguridad: no fumar ni acercarse a llamas con el oxígeno puesto. Mantener el equipo alejado de fuentes de calor.</li><li>Cuidado de las gafas nasales: limpiar diariamente con agua, cambiarlas regularmente para evitar lesiones en las alas de la nariz.</li><li>Con oxígeno puede salir de casa: existen equipos portátiles (concentradores portátiles, botellas de oxígeno líquido) que facilitan la vida activa.</li></ul>
` },
  { id:"epoc-5", titulo:"EPOC · Exacerbación, seguimiento y complicaciones", min:4, html:`
<h3>Exacerbación de la EPOC: reconocimiento y actuación</h3>
<p><strong>Definición:</strong> empeoramiento agudo de los síntomas respiratorios (disnea, tos, expectoración) que va más allá de la variación diaria normal y que requiere un cambio en el tratamiento.</p>
<h4>Síntomas de exacerbación</h4>
<ul><li>Aumento de la disnea respecto al nivel habitual.</li><li>Aumento de la cantidad de expectoración.</li><li>Cambio en el color/aspecto del esputo: de blanco a amarillo o verdoso (sugiere infección bacteriana).</li><li>Aumento de la tos.</li><li>Síntomas sistémicos: fiebre, malestar general.</li></ul>
<h4>Evaluación de gravedad</h4>
<div class="tbl-scroll"><table><tr><th>Gravedad</th><th>Criterios y manejo</th></tr><tr><td><strong>Leve</strong></td><td>Puede manejarse con ajuste del tratamiento habitual sin necesidad de nuevos fármacos o con adición de un broncodilatador de rescate. Tratamiento en AP.</td></tr><tr><td><strong>Moderada</strong></td><td>Requiere tratamiento con antibiótico y/o corticoide oral. Puede manejarse en AP con seguimiento estrecho.</td></tr><tr><td><strong>Grave</strong></td><td>Disnea intensa, SatO2 < 90%, frecuencia respiratoria > 25 rpm, alteración del nivel de consciencia, fracaso del tratamiento ambulatorio → urgencias hospitalarias.</td></tr></table></div>
<div class="callout truco"><p><strong>Señales de alarma: derivación urgente a urgencias hospitalarias</strong></p><p>→ SatO2 < 90% que no mejora con broncodilatador.</p><p>→ Frecuencia respiratoria > 30 rpm.</p><p>→ Uso intenso de musculatura accesoria, respiración paradójica.</p><p>→ Alteración del nivel de consciencia (confusión, somnolencia).</p><p>→ Cianosis central.</p><p>→ Incapacidad para hablar frases completas por la disnea.</p><p>→ Fracaso del tratamiento ambulatorio a las 24-48h.</p></div>
<h4>Plan de acción ante exacerbación (PAE)</h4>
<p>El PAE es un documento personalizado que el paciente tiene en casa y que le indica qué hacer cuando empeora. Enfermería colabora en su elaboración y en asegurarse de que el paciente lo conoce y lo tiene actualizado.</p>
<ul><li>Zona verde: síntomas estables. Continuar tratamiento habitual.</li><li>Zona amarilla: empeoramiento leve-moderado. Aumentar broncodilatador de rescate. Llamar a la consulta de enfermería o médico.</li><li>Zona roja: empeoramiento grave (señales de alarma anteriores). Llamar al 112 o acudir a urgencias. Iniciar corticoide oral si está prescrito como rescate.</li></ul>
<h3>Seguimiento y complicaciones</h3>
<h4>Calendario de seguimiento en EPOC estable</h4>
<div class="tbl-scroll"><table><tr><th>Situación</th><th>Frecuencia y actividades</th></tr><tr><td><strong>EPOC leve (GOLD 1)</strong></td><td>Visita anual. Espirometría anual. Consejo antitabaco. Revisión de inhaladores.</td></tr><tr><td><strong>EPOC moderada (GOLD 2)</strong></td><td>Visita cada 6 meses. Espirometría anual. Cuestionario CAT o mMRC. Revisión de inhaladores. Vacunación.</td></tr><tr><td><strong>EPOC grave (GOLD 3-4)</strong></td><td>Visita cada 3 meses. Espirometría semestral o anual. Saturación de O2. Valoración de OCD. Coordinación con neumología.</td></tr><tr><td><strong>Tras exacerbación</strong></td><td>Visita de seguimiento en 1-2 semanas. Revisar causas, tratamiento, técnica y plan de acción.</td></tr></table></div>
<h4>Complicaciones a detectar</h4>
<div class="tbl-scroll"><table><tr><th>Complicación</th><th>Descripción y actuación enfermera</th></tr><tr><td><strong>Insuficiencia respiratoria crónica</strong></td><td>SatO2 < 92% en reposo de forma mantenida. Indicación potencial de OCD.</td></tr><tr><td><strong>Cor pulmonale</strong></td><td>Hipertensión pulmonar por hipoxemia crónica → insuficiencia cardíaca derecha. Edemas en MMII, ingurgitación yugular, hepatomegalia.</td></tr><tr><td><strong>Poliglobulia</strong></td><td>Respuesta adaptativa a la hipoxemia crónica. Hematocrito elevado, cefalea, rubicundez.</td></tr><tr><td><strong>Ansiedad y depresión</strong></td><td>Muy prevalentes en EPOC. Valorar en cada visita. Derivar a psicología o psiquiatría si es necesario.</td></tr><tr><td><strong>Pérdida de peso y sarcopenia</strong></td><td>Marcadores de mal pronóstico. Derivar a nutricionista. Valorar suplementación nutricional.</td></tr><tr><td><strong>Osteoporosis</strong></td><td>Favorecida por el uso de corticoides y la inactividad física. Valorar densitometría.</td></tr></table></div>
<p><em>Apuntes para estudiantes de enfermería · Centro de Salud Palma Norte · SERMAS</em></p>
<p><em>Tutora de prácticas: Ana Domínguez Rodríguez · EPOC · Cartera de Servicios SERMAS</em></p>
` }
  ]
});
